import {describe,it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {templates,ARM_LOCK,validateArmParameters} from './armContract'
import {mapArm} from './armMapping'
import {armFixture} from './testing/armFixture'
import {newProject,newRecord,parseProject,canonical,sanitize} from './project'
import {collections,settings} from './catalog'
import {assess} from './assessment'
import {subnetMask} from './networkMath'
import {armReview,ARM_EFFECTS} from './armReview'
import {validateArmApi,apiDefinition} from './armApi'
import {exportFiles,schedules,designMarkdown,implementationMarkdown,adapterStatus} from './exports'
describe('pinned ARM input mapping (not native deployment qualification)',()=>{
 for(const identity of ['ad','local'] as const){
  it(`${identity}: pins exact unmodified source bytes and explicitly maps every parameter`,()=>{const pin=ARM_LOCK.templates.find(t=>t.id===identity)!,bytes=readFileSync(new URL(`./contracts/arm/${pin.file}`,import.meta.url));expect(createHash('sha256').update(bytes).digest('hex')).toBe(pin.sha256);const p=armFixture(identity),result=mapArm(p);expect(result.findings).toEqual([]);expect(Object.keys(result.parameters).sort()).toEqual(Object.keys(templates[identity].parameters).sort());expect(result.mappings.map(m=>m.parameter).sort()).toEqual(Object.keys(result.parameters).sort());expect(validateArmParameters(templates[identity],result.document)).toEqual([]);expect(parseProject(canonical(p))).toEqual(p);expect(result.document.parameters.localAdminPassword).toHaveProperty('reference');expect(result.parameters).toHaveProperty('enableStorageAutoIp',{value:false})})
  it(`${identity}: detects incorrect parameter names, types, enums and secure literals`,()=>{const result=mapArm(armFixture(identity)),input:any=structuredClone(result.document);input.parameters.deploymentMode.value='WhatIf';input.parameters.logsRetentionInDays.value=366;input.parameters.arcNodeResourceIds.value='bad';input.parameters.localAdminPassword={value:'never-export-this'};input.parameters.unknown={value:true};delete input.parameters.enableStorageAutoIp;const errors=validateArmParameters(templates[identity],input);for(const name of ['deploymentMode','logsRetentionInDays','arcNodeResourceIds','localAdminPassword','unknown','enableStorageAutoIp'])expect(errors.some(e=>e.includes(name))).toBe(true)})
 }
 it('keeps AD and local identity consumer inputs distinct',()=>{const ad=mapArm(armFixture()),local=mapArm(armFixture('local'));expect(ad.parameters).not.toHaveProperty('identityProvider');expect(local.parameters).not.toHaveProperty('AzureStackLCMAdminPassword');expect(local.parameters.identityProvider).toEqual({value:'LocalIdentity'});expect(local.parameters.dnsZones).toEqual({value:[{dnsZoneName:'synthetic.test',dnsForwarder:['192.0.2.5']}]})})
 it('does not infer ARM work from retained portal inputs',()=>{const p=armFixture();p.config.architecture.route='portal';p.config.arm.keyVault='missing';expect(mapArm(p).findings).toEqual([]);expect(mapArm(p).mappings).toEqual([]);expect(assess(p).some(f=>f.group==='arm')).toBe(false);expect(p.config.arm.keyVault).toBe('missing')})
 it('rejects malformed secret references and never substitutes a missing credential',()=>{const p=armFixture();p.records.armSecretBindings[0].values.secretVersion='not-a-version';expect(mapArm(p).findings.some(f=>f.message.includes('malformed Key Vault'))).toBe(true);p.records.armSecretBindings=[];expect(mapArm(p).parameters).not.toHaveProperty('localAdminPassword');expect(mapArm(p).findings.some(f=>f.message.includes('exactly one'))).toBe(true)})
 it('requires explicit secret bindings and matches source vault, secret and version',()=>{const p=armFixture();p.config.arm.localAdminSecret='keyvault://other-vault/local';p.records.armSecretBindings[0].values.reference=p.config.arm.localAdminSecret;expect(mapArm(p).findings.some(f=>f.field==='reference')).toBe(true);p.records.armSecretBindings.push(structuredClone(p.records.armSecretBindings[0]));expect(mapArm(p).parameters).not.toHaveProperty('localAdminPassword')})
 it('rejects a fake GUID in an otherwise shaped Key Vault resource reference',()=>{const result=mapArm(armFixture()),input:any=structuredClone(result.document);input.parameters.localAdminPassword.reference.keyVault.id='/subscriptions/------------------------------------/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/vault';expect(validateArmParameters(templates.ad,input).some(e=>e.includes('malformed Key Vault'))).toBe(true)})
 it('preserves resource intent and refuses unsupported witness behavior',()=>{const p=armFixture(),before=canonical(p);p.records.azureResources.find(r=>r.id===p.config.arm.witnessAccount)!.values.lifecycle='existing-preserve';expect(mapArm(p).findings.some(f=>f.category==='preservation')).toBe(true);p.config.azure.witness='file-share';expect(mapArm(p).findings.some(f=>f.field==='witness')).toBe(true);expect(before).not.toBe(canonical(p));const unchanged=canonical(p);mapArm(p);expect(canonical(p)).toBe(unchanged)})
 it.each([['storage','san'],['topology','rack-aware'],['intent','extend'],['release','future']])('blocks unsupported architecture %s=%s',(key,value)=>{const p=armFixture();p.config.architecture[key]=value;expect(mapArm(p).findings.some(f=>f.group==='architecture'&&f.field===key)).toBe(true)})
 it('does not turn operator review or Validate mode into runtime qualification',()=>{const p=armFixture();expect(mapArm(p).consumer).toHaveProperty('commit');expect(ARM_LOCK.qualification).toBe('design-only');p.config.arm.deploymentMode='Deploy';expect(mapArm(p).findings.some(f=>f.field==='priorValidation')).toBe(true);p.config.arm.priorValidation='operator-reported deployment ID';expect(ARM_LOCK.qualification).toBe('design-only')})
 it('blocks host/pool overlap and repeated host or Arc identities',()=>{const p=armFixture();p.records.nodes[1].values.managementIp='192.0.2.100';p.records.nodes[1].values.name=p.records.nodes[0].values.name;p.records.nodes[1].values.arcId=p.records.nodes[0].values.arcId;const fields=mapArm(p).findings.map(f=>f.field);expect(fields).toEqual(expect.arrayContaining(['name','arcId','managementIp']))})
 it('matches adapter aliases case-insensitively but rejects duplicates and missing node ports',()=>{const p=armFixture();p.records.adapters[2].values.osName='PNIC1';expect(mapArm(p).findings).toEqual([]);p.records.adapters[3].values.osName='PNIC1';expect(mapArm(p).findings.some(f=>f.group==='intents')).toBe(true)})
 it('separates automatic storage addressing from retained explicit observations',()=>{const p=armFixture();p.config.arm.enableStorageAutoIp=true;const mapped=mapArm(p);expect(mapped.findings).toEqual([expect.objectContaining({severity:'info',field:'enableStorageAutoIp'})]);expect(JSON.stringify(mapped.parameters.storageNetworkList)).not.toContain('storageAdapterIPInfo');expect(p.records.storageAddresses).toHaveLength(4)})
 it('rejects duplicate storage addresses and SAN I/O substituted for S2D networks',()=>{const p=armFixture();p.records.storageAddresses[1].values.ip=p.records.storageAddresses[0].values.ip;expect(mapArm(p).findings.some(f=>f.group==='storageAddresses'&&f.field==='ip')).toBe(true);p.records.networks[1].values.role='iscsi';expect(mapArm(p).findings.some(f=>f.group==='armStorageNetworks'&&f.field==='network')).toBe(true)})
 it('retains unsupported OEM credential requirements without emitting a non-secure credential array',()=>{const p=armFixture();p.records.sbeCredentials=[newRecord('sbeCredentials')];const result=mapArm(p);expect(result.parameters.partnerCredentiallist).toEqual({value:[]});expect(result.findings.some(f=>f.group==='sbeCredentials')).toBe(true)})
 it('does not automatically create workload CSVs over an explicit design',()=>{const p=armFixture();p.config.arm.configurationMode='Express';const volume=newRecord('volumes');volume.values.role='workload';p.records.volumes.push(volume);expect(mapArm(p).findings.some(f=>f.field==='configurationMode')).toBe(true)})
 it('migrates schema 5 with explicit unresolved ARM defaults and rejects smuggled future groups',()=>{const p=newProject(),old=structuredClone(p);old.schemaVersion=5;for(const g of settings){if((g.since??1)>5){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>5)delete old.config[g.key][f.key]}for(const g of collections){if((g.since??1)>5)delete old.records[g.key]}const migrated=parseProject(canonical(old));expect(migrated).toEqual(p);expect(migrated.config.arm.configurationMode).toBe('unresolved');old.config.arm=p.config.arm;expect(()=>parseProject(canonical(old))).toThrow('unknown field')})
 it('removes operational bindings from sanitized copies and keeps them non-executable',()=>{const p=sanitize(armFixture());expect(canonical(p)).not.toContain('synthetic-vault');expect(mapArm(p).findings.some(f=>f.message.includes('Sanitized'))).toBe(true)})
 it('calculates exact masks and rejects invalid prefixes',()=>{expect(subnetMask(0)).toBe('0.0.0.0');expect(subnetMask(23)).toBe('255.255.254.0');expect(subnetMask(32)).toBe('255.255.255.255');for(const prefix of [-1,33,24.5,NaN])expect(()=>subnetMask(prefix)).toThrow()})
 it('rejects unknown nested API keys, incorrect property types and unsupported enums',()=>{const input:any=mapArm(armFixture()).document;input.parameters.intentList.value[0].unexpected=true;input.parameters.intentList.value[0].adapterPropertyOverrides={jumboPacket:9014,networkDirect:'1',networkDirectTechnology:'Ethernet'};input.parameters.storageNetworkList.value[0].storageAdapterIPInfo[0].subnetMask=24;input.parameters.dnsServers.value=[7];const errors=validateArmParameters(templates.ad,input);for(const name of ['unexpected','jumboPacket','networkDirectTechnology','subnetMask','dnsServers'])expect(errors.some(e=>e.includes(name))).toBe(true)})
 it('pins API definitions and licenses to exact Microsoft source bytes',()=>{for(const pin of [...ARM_LOCK.apiSources,...ARM_LOCK.licenses]){const bytes=readFileSync(new URL(`./contracts/arm/${pin.file}`,import.meta.url));expect(createHash('sha256').update(bytes).digest('hex')).toBe(pin.sha256);if('blobSha'in pin)expect(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex')).toBe(pin.blobSha)}})
 it('uses actual Microsoft nested API types and common enums without coercion or mutation',()=>{const parameters:any=mapArm(armFixture('local')).parameters;parameters.identityProvider.value='InventedIdentity';parameters.intentList.value[0].overrideQosPolicy='true';parameters.storageNetworkList.value[0].vlanId=711;const before=JSON.stringify(parameters),errors=validateArmApi(parameters);expect(errors.some(e=>e.includes('/identityProvider'))).toBe(true);expect(errors.some(e=>e.includes('overrideQosPolicy'))).toBe(true);expect(errors.some(e=>e.includes('vlanId'))).toBe(true);expect(JSON.stringify(parameters)).toBe(before);expect(()=>apiDefinition({$ref:'https://unreviewed.example/schema'})).toThrow('Unqualified');expect(()=>apiDefinition({$ref:'#/definitions/NotARealDefinition'})).toThrow('Missing')})
 it('rejects secret values in the non-secure OEM parameter even if its shape matches the API',()=>{const input:any=mapArm(armFixture()).document;input.parameters.partnerCredentiallist={value:[{name:'credential',value:'must-not-ship'}]};expect(validateArmParameters(templates.ad,input).some(e=>e.includes('non-secure credentials'))).toBe(true)})
 it('keeps review output, schedules, reports and adapter status consistent',async()=>{const p=armFixture(),review=armReview(p),files=await exportFiles(p,false,false);expect(JSON.parse(String(files['plans/arm-mapping-review.json']))).toEqual(review);expect(review).toMatchObject({qualification:'design-only',executionReady:false,runtimeQualified:false});expect(review.candidateParameters).toEqual(mapArm(p).document);expect(schedules(p)['ARM mappings']).toHaveLength(55);for(const effect of ARM_EFFECTS){expect(designMarkdown(p)).toContain(effect);expect(implementationMarkdown(p)).toContain(effect)}expect(adapterStatus(p).find(a=>a.id==='arm')).toMatchObject({qualification:'design-only',executionReady:false});const shared=await exportFiles(p,true,false);expect(JSON.parse(String(shared['plans/arm-mapping-review.json'])).candidateParameters).toBeNull();expect(Object.keys(files)).not.toContain('arm/azuredeploy.parameters.json')})
})
