import {describe,it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {armFixture} from './testing/armFixture'
import {mapArm} from './armMapping'
import {templates,type ArmTemplate} from './armContract'
import {armEvaluator,parseArmExpression} from './armExpressions'
import {inspectArmDeployment} from './armDeployment'
import {validateArmDeploymentBody} from './armApi'
import {armReview} from './armReview'
import {sanitize} from './project'
import toolchain from './contracts/arm/toolchain.json'
const context={cloud:'AzureCloud',subscription:'11111111-1111-1111-1111-111111111111',resourceGroup:'synthetic-rg'}
const fixture=(identity:'ad'|'local'='ad')=>{const p=armFixture(identity);p.config.arm.sbeManifestCreationDate='2026-09-11T12:00:00Z';return mapArm(p).parameters}
describe('actual pinned deployment body and resource conditions',()=>{
 for(const identity of ['ad','local'] as const)for(const mode of ['Validate','Deploy'])it(`${identity}/${mode}: evaluates full deploymentSettings inputs and stage resource conditions`,()=>{const parameters=fixture(identity);parameters.deploymentMode={value:mode};const result=inspectArmDeployment(templates[identity],parameters,context);expect(result.issues).toEqual([]);expect(result.runtimeQualified).toBe(false);expect(result.deploymentSettings).toMatchObject({deploymentMode:mode,deploymentConfiguration:{version:'10.0.0.0'}});expect(result.resources.find(r=>r.symbol==='HCICluster')!.active).toBe(mode==='Validate');expect(result.resources.find(r=>r.symbol==='edgeDevices')!.count).toBe(mode==='Validate'?2:0);expect(result.resources.find(r=>r.symbol==='KVWitnessSecret')!.active).toBe(true);expect(result.resources.find(r=>r.symbol==='KVPartnerCreds')!.count).toBe(0);expect(result.resources.find(r=>r.symbol==='KVConfigurations')!.active).toBe(false)})
 it('exposes the source null SBE timestamp mismatch instead of treating parameter types as full validation',()=>{const p=armFixture();p.config.arm.sbeManifestCreationDate='';const mapped=mapArm(p),result=inspectArmDeployment(templates.ad,mapped.parameters,context);expect(result.issues).toEqual([expect.objectContaining({path:'/deploymentConfiguration/scaleUnits/0/sbePartnerInfo/sbeDeploymentInfo/sbeManifestCreationDate'})]);expect(mapped.findings.some(f=>f.field==='sbeManifestCreationDate')).toBe(true)})
 it('validates date-time and secret URI formats against the complete API definition',()=>{const parameters=fixture();parameters.sbeManifestCreationDate={value:'not-a-timestamp'};const result=inspectArmDeployment(templates.ad,parameters,context);expect(result.issues.some(e=>e.message.includes('date-time'))).toBe(true);const body:any=inspectArmDeployment(templates.ad,fixture(),context).deploymentSettings;body.deploymentConfiguration.scaleUnits[0].deploymentData.secrets[0].secretLocation='not-a-uri';expect(validateArmDeploymentBody(body).some(e=>e.message.includes('uri'))).toBe(true)})
 it('resolves sovereign witness/vault endpoints from actual variables',()=>{const result=inspectArmDeployment(templates.local,fixture('local'),{...context,cloud:'AzureUSGovernment'});expect(result.issues).toEqual([]);const body:any=result.deploymentSettings,data=body.deploymentConfiguration.scaleUnits[0].deploymentData;expect(data.cluster.azureServiceEndpoint).toBe('core.usgovcloudapi.net');expect(data.secrets.every((s:any)=>s.secretLocation.startsWith('https://synthetic-vault.vault.usgovcloudapi.net/secrets/'))).toBe(true);expect(data.secrets).toHaveLength(2)})
 it('evaluates new-vault conditions without assuming they suppress the unconditional witness',()=>{const parameters=fixture();parameters.createNewKeyVault={value:true};parameters.witnessType={value:'No Witness'};const result=inspectArmDeployment(templates.ad,parameters,context);for(const symbol of ['KVConfigurations','StorageAccountConfigurations','KVDiagnosticsConfig','witnessStorageAcc','KVWitnessSecret'])expect(result.resources.find(r=>r.symbol===symbol)!.active).toBe(true)})
 it('keeps full API body checks strict without deleting unknown or read-only properties',()=>{const body:any=inspectArmDeployment(templates.ad,fixture(),context).deploymentSettings;body.reportedProperties={};body.deploymentConfiguration.scaleUnits[0].deploymentData.storage.unsupportedField=true;const before=JSON.stringify(body),errors=validateArmDeploymentBody(body);expect(errors.some(e=>e.message.includes('reportedProperties'))).toBe(true);expect(errors.some(e=>e.message.includes('unsupportedField'))).toBe(true);expect(JSON.stringify(body)).toBe(before)})
 it('fails closed on changed or unresolved template expressions',()=>{const changed=structuredClone(templates.ad);(changed.resources.DeploymentSettings as any).properties.deploymentMode="[reference('live-resource').mode]";const result=inspectArmDeployment(changed,fixture(),context);expect(result.issues.some(e=>e.message.includes('no reviewed offline implementation'))).toBe(true);expect(result.deploymentSettings).toBeNull()})
 it('maps the synthetic AD and local fixtures without findings',()=>{for(const identity of ['ad','local'] as const){const p=armFixture(identity);p.config.arm.sbeManifestCreationDate='2026-09-11T12:00:00Z';expect(mapArm(p).findings).toEqual([])}})
 it('retains historical ARM-TTK evidence consistent with the pinned toolchain without claiming deployment success',()=>{for(const identity of ['ad','local'] as const){const evidence=JSON.parse(readFileSync(new URL(`../docs/evidence/arm-ttk-20260911/${identity}.json`,import.meta.url),'utf8'));expect(evidence).toMatchObject({toolCommit:toolchain.commit,parameterChecksPassed:true,passedChecks:30,failedSourceChecks:6,runtimeQualified:false});expect(evidence.checks.filter((c:any)=>!c.passed).map((c:any)=>c.name).sort()).toEqual(toolchain.knownSourceFindings.map(f=>f.name).sort())}const bad=JSON.parse(readFileSync(new URL('../docs/evidence/arm-ttk-20260911/negative-keyvault-reference.json',import.meta.url),'utf8'));expect(bad.parameterChecksPassed).toBe(false);expect(bad.checks.some((c:any)=>c.name==='DeploymentParameters Should Have Value'&&!c.passed)).toBe(true)})
 it('keeps evaluated project resources and settings out of the sanitized review',()=>{const p=armFixture();expect(armReview(p).inspection?.deploymentSettings).not.toBeNull();const shared=armReview(sanitize(p));expect(shared.inspection).toBeNull();expect(shared.candidateParameters).toBeNull();expect(shared.toolkit.qualification).toContain('source-findings-open')})
 it('requires complete serialized native evidence summaries rather than null property projections',()=>{const summary=JSON.parse(readFileSync(new URL('../docs/evidence/arm-ttk-20260911/summary.json',import.meta.url),'utf8'));expect(summary.map((r:any)=>r.identity)).toEqual(['ad','local']);for(const row of summary){const captured=JSON.parse(readFileSync(new URL(`../docs/evidence/arm-ttk-20260911/${row.identity}.json`,import.meta.url),'utf8'));expect(row).toMatchObject({sourceCommit:captured.sourceCommit,templateSha256:captured.templateSha256,parameterSha256:captured.parameterSha256,parameterChecksPassed:true,passedChecks:30,failedSourceChecks:6,runtimeQualified:false})}})
})
describe('bounded offline ARM expression semantics',()=>{
 const evaluate=(source:string)=>armEvaluator(templates.ad,fixture(),context).evaluate(source)
 it('preserves documented case-sensitive equals and case-insensitive function/input lookup',()=>{expect(evaluate("[equals('ABC', 'abc')]")).toBe(false);expect(evaluate("[PARAMETERS('CLUSTERNAME')]")).toBe('synthetic-hci');expect(evaluate("[contains('Abc','abc')]")).toBe(false)})
 it('evaluates lazy branches and escaped strings without resolving secrets',()=>{expect(evaluate("[if(equals(1,1),'safe',parameters('localAdminPassword'))]")).toBe('safe');expect(()=>evaluate("[parameters('localAdminPassword')]")).toThrow('Runtime secret');expect(evaluate("[concat('O''Brien',' node')]")).toBe("O'Brien node");expect(evaluate('[[literal]')).toBe('[literal]')})
 it('resolves variable copy expressions and detects cyclic variables',()=>{expect(evaluate("[variables('isNodeNameValid')]")).toEqual(['true','true']);const t:ArmTemplate={parameters:{},resources:{},variables:{a:"[variables('b')]",b:"[variables('a')]"}};expect(()=>armEvaluator(t,{},context).evaluate("[variables('a')]")).toThrow('Cyclic')})
 it('rejects unsupported syntax, functions, wrong arity and invalid loops',()=>{for(const source of ["[if(equals(1,1),'unterminated)]","[concat('a') extra]","[listKeys('live','api')]","[equals(1)]","[copyIndex()]","[parameters('arcNodeResourceIds')[999]]"]){expect(()=>evaluate(source)).toThrow()}expect(()=>parseArmExpression(' '.repeat(5))).toThrow();const runner=armEvaluator(templates.ad,fixture(),context);for(const count of [-1,2001,1.5])expect(()=>runner.count(count)).toThrow()})
 it('does not interpret expressions embedded in operator parameter values',()=>{const parameters=fixture();parameters.clusterName={value:"[listKeys('do-not-evaluate','api')]"};expect(armEvaluator(templates.ad,parameters,context).evaluate("[parameters('clusterName')]")).toBe("[listKeys('do-not-evaluate','api')]");expect(()=>evaluate("[equals(json('{}'),json('{}'))]")).toThrow('outside this pinned scalar')})
})
