import type {Project} from './project'
import {ARM_LOCK} from './armContract'
import {ARM_SHAPE_SOURCE} from './armShapes'
import {mapArm} from './armMapping'
import toolchain from './contracts/arm/toolchain.json'
export {toolchain as ARM_TOOLCHAIN}
export const ARM_EFFECTS=[
 'Both Validate and Deploy submit resource changes. Validate is not a read-only preflight.',
 'The templates create or update the Azure Local cluster, edge devices, role assignments, credential secrets and witness storage resources.',
 'The witness account and witness secret are unconditional. A preserved witness or a no-witness design needs a different qualified consumer.',
 'Creating a new vault also declares diagnostic storage and diagnostic settings. The pinned new-vault resource sets enableSoftDelete=false; current service behavior requires review.',
 'Existing deployment vaults still receive secrets and role assignments. Secret resolution requires an existing source vault enabled for template deployment and deployment-principal Microsoft.KeyVault/vaults/deploy/action access.',
 'HVCI, DRTM and side-channel mitigation are fixed true in the pinned deployment settings. These fixed choices need reconciliation with the selected security design.',
 'SAN attachment, explicit CSV/storage-path creation and post-cluster Arc SDN are separate handoffs; these templates do not implement the complete design.',
] as const
export function armReview(p:Project){const mapping=mapArm(p);return {kind:'azurelocal-arm-mapping-review',version:'0.1.0',projectId:p.id,revision:p.revision,requested:mapping.requested,identity:mapping.identity,qualification:'design-only',executionReady:false,runtimeQualified:false,consumer:mapping.consumer,apiVersion:ARM_LOCK.apiVersion,apiSchemaQualification:ARM_LOCK.apiSchemaQualification,shapeSource:ARM_SHAPE_SOURCE,toolkit:{repository:toolchain.repository,commit:toolchain.commit,version:toolchain.version,qualification:toolchain.qualification,knownSourceFindings:toolchain.knownSourceFindings,basis:'Synthetic reference fixtures tested in native PowerShell; this project has not been submitted.'},resourceEffects:ARM_EFFECTS,inspection:mapping.requested&&!p.sharing?mapping.inspection:null,findings:mapping.findings,mappings:mapping.mappings,candidateParameters:mapping.requested&&!p.sharing?mapping.document:null,limitations:ARM_LOCK.knownLimitations}}
export function armReportRows(p:Project):unknown[][]{const r=armReview(p);return [['ARM route requested',r.requested],['Identity template',r.identity],['Consumer commit',r.consumer.commit],['Template SHA-256',r.consumer.sha256],['Qualification',r.qualification],['Native runtime qualified',false],['Reference toolkit',`ARM-TTK ${toolchain.version}; ${toolchain.commit}`],['Reference toolkit result',toolchain.qualification],['API contract',`${r.apiVersion}; ${r.apiSchemaQualification}`],['Mapping corrections',r.findings.filter(f=>f.severity==='error').length],['Evaluated deployment settings',r.inspection?.deploymentSettings?'Offline source evaluation; runtime unqualified':'Unavailable'],['Active top-level resource instances',r.inspection?(r.inspection.resources.some(r=>r.count===null)?'Unresolved':r.inspection.resources.reduce((sum,r)=>sum+r.count!,0)):'Not evaluated'],...ARM_EFFECTS.map(effect=>['Resource effect / boundary',effect])]}
export function armSchedules(p:Project){const review=armReview(p);return {'ARM review':[['Field','Value'],...armReportRows(p)],'ARM resources':[['Symbol','Resource type','API version','Active','Instances','Names','Writes secrets','Nested deployment'],...(review.inspection?.resources??[]).map(r=>[r.symbol,r.type,r.apiVersion,r.active??'Unknown',r.count??'Unknown',r.names.join(', '),r.writesSecrets,r.nestedTemplate])],'ARM mappings':[['Parameter','Design source','Stable record IDs'],...review.mappings.map(m=>[m.parameter,m.source,m.recordIds.join(', ')])]}}
