import {describe,it,expect} from 'vitest'
import {newProject,newRecord,canonical} from './project'
import {assess,storageBudgets,bytes,resiliencyFactor,dependencyOrder,computeBudget,ipv4,subnet} from './assessment'
import {exportFiles,stagePlan,drawio,csv,xlsx} from './exports'
import {load} from 'js-yaml'
import * as XLSX from 'xlsx'
function fixture(storage='s2d',identity='ad'){const p=newProject();p.config.architecture.storage=storage;p.config.architecture.identity=identity;p.config.architecture.osBuild='26100.1234';for(let i=0;i<2;i++){const node=newRecord('nodes');node.values.name=`node-${i+1}`;node.values.cores=32;node.values.memoryGiB=256;p.records.nodes.push(node)}return p}
describe('release and architecture gates',()=>{
 it.each(['ad','local'])('blocks SAN-only Arc SDN for %s and retains intent',identity=>{const p=fixture('san',identity),before=canonical(p);expect(assess(p).some(f=>f.message.includes('SAN-only 2604'))).toBe(true);expect(canonical(p)).toBe(before)})
 it.each(['s2d','hybrid'])('retains %s Arc SDN without a false SAN-only block',storage=>{expect(assess(fixture(storage)).some(f=>f.message.includes('SAN-only 2604'))).toBe(false)})
 it('requires local identity vault/account but no AD preparation',()=>{const p=fixture('s2d','local');const issues=assess(p);expect(issues.some(x=>x.field==='vault')).toBe(true);expect(issues.some(x=>x.field==='ou'||x.field==='deploymentAccount')).toBe(false)})
 it('preserves existing Arc SDN on opt-out and omits NC/policy execution stages',()=>{const p=fixture();p.config.sdn.enabled=false;p.config.sdn.existingState='arc-enabled';expect(assess(p).some(f=>f.category==='preservation')).toBe(true);expect(stagePlan(p).stages.some(s=>s.id.startsWith('sdn-'))).toBe(false)})
 it('rejects existing on-prem controller and unsupported intent ownership',()=>{const p=fixture();p.config.sdn.existingState='onprem-controller';const port=newRecord('adapters');port.values.ownership='san-io';port.values.intent='missing';p.records.adapters=[port];expect(assess(p).some(f=>f.message.includes('On-premises NC conflicts'))).toBe(true);expect(assess(p).some(f=>f.message.includes('SAN I/O ports'))).toBe(true)})
 it('enforces typed references and detects dependency cycles',()=>{const p=fixture();const a=newRecord('management'),b=newRecord('bootstrapTasks');p.records.management=[a];p.records.bootstrapTasks=[b];for(const [from,to]of [[a.id,b.id],[b.id,a.id]]){const d=newRecord('dependencies');d.values.from=from;d.values.to=to;p.records.dependencies.push(d)}expect(dependencyOrder(p).cyclicOrBlocked).toHaveLength(2);p.records.nodes[0].values.site=a.id;expect(assess(p).some(f=>f.group==='nodes'&&f.field==='site'&&f.category==='reference')).toBe(true)})
 it('protects existing data LUNs and requires NTFS for SAN CSVs',()=>{const p=fixture('san'),lun=newRecord('luns'),volume=newRecord('volumes');lun.values.existingData=true;volume.values.source='san';volume.values.lun=lun.id;p.records.luns=[lun];p.records.volumes=[volume];expect(assess(p).some(f=>f.field==='lifecycle'&&f.category==='preservation')).toBe(true);expect(assess(p).some(f=>f.field==='filesystem')).toBe(true)})
})
describe('capacity and network math',()=>{
 it('normalizes explicit decimal and binary units',()=>{expect(bytes(1,'TB')).toBe(1e12);expect(bytes(1,'TiB')).toBe(1099511627776);expect(bytes(1000,'GB')).toBe(bytes(1,'TB'))})
 it('does not clamp unsupported resiliency into a passing layout',()=>{expect(resiliencyFactor('nested-two-way',2,0)).toBe(4);expect(resiliencyFactor('nested-two-way',3,0)).toBeNull();expect(resiliencyFactor('three-way-mirror',2,0)).toBeNull();expect(resiliencyFactor('mirror-accelerated-parity',4,20)).toBeCloseTo(2.2);expect(resiliencyFactor('dual-parity',3,0)).toBeNull();expect(resiliencyFactor('dual-parity',5,0)).toBe(2)})
 it('counts source budgets and reserve once; SAN cannot hide S2D overcommit',()=>{const p=fixture('hybrid'),pool=newRecord('pools'),device=newRecord('devices'),volume=newRecord('volumes'),array=newRecord('arrays');pool.values.reserveBytes=1e12;device.values.pool=pool.id;device.values.node=p.records.nodes[0].id;device.values.size=5;device.values.count=1;volume.values.pool=pool.id;volume.values.size=5;array.values.capacity=100;array.values.evidence='operator-ref';p.records.pools=[pool];const secondDevice=newRecord('devices');secondDevice.values={...device.values,node:p.records.nodes[1].id};p.records.devices=[device,secondDevice];p.records.volumes=[volume];p.records.arrays=[array];const [s2d,san]=storageBudgets(p);expect(s2d.remainingBytes).toBe(-1e12);expect(san.remainingBytes).toBe(100e12);expect(assess(p).some(f=>f.category==='capacity'&&f.record===pool.id)).toBe(true)})
 it('accounts linked management once and reserves largest node capacity',()=>{const p=fixture(),m=newRecord('management'),w=newRecord('workloads');m.values.hosting='target-cluster';m.values.count=1;m.values.cpu=8;m.values.memoryGiB=16;w.values.managementComponent=m.id;w.values.count=1;w.values.vcpu=8;w.values.memoryGiB=16;p.records.management=[m];p.records.workloads=[w];p.config.capacity.failureReserveNodes=1;const c=computeBudget(p);expect(c.demandVCpu).toBe(8);expect(c.availableVCpu).toBe(32);expect(c.demandMemoryGiB).toBe(16)})
 it('validates exact IPv4 literals and detects overlapping scoped networks',()=>{expect(ipv4('999.1.1.1')).toBeNull();expect(ipv4('01.2.3.4')).toBeNull();expect(subnet('192.0.2.0/24')).toEqual({start:3221225984,end:3221226239,prefix:24});const p=fixture();for(const cidr of ['192.0.2.0/24','192.0.2.128/25']){const n=newRecord('networks');n.values.cidr=cidr;n.values.routingScope='same';p.records.networks.push(n)}expect(assess(p).some(f=>f.message.includes('subnets overlap'))).toBe(true)})
})
describe('export consistency and injection guards',()=>{
 it('round trips canonical YAML and generates deterministic draft manifest without execution',async()=>{const p=fixture();const a=await exportFiles(p,false,false),b=await exportFiles(p,false,false);expect(a).toEqual(b);expect(load(String(a['environment.yml']))).toEqual(p);expect(JSON.parse(String(a['plans/stages.json'])).executionAuthorized).toBe(false);expect(JSON.parse(String(a['manifest.json'])).files.length).toBe(Object.keys(a).length-1)})
 it('escapes XML and spreadsheet formulas without corrupting project strings',()=>{const p=fixture();p.records.nodes[0].values.name='=HYPERLINK("https://example.test")<node>';expect(drawio(p)).toContain('&lt;node&gt;');expect(csv([[' =1+1']])).toContain("' =1+1");const workbook=XLSX.read(xlsx(p),{type:'array'});const rows=XLSX.utils.sheet_to_json(workbook.Sheets.nodes,{header:1}) as unknown[][];expect(String(rows[1][1])).toMatch(/^'=/);expect(workbook.Sheets.nodes.B2.f).toBeUndefined()})
})
