import {it,expect} from 'vitest'
import {newProject,newRecord,canonical,parseProject,sanitize} from './project'
import {automationReview,automationFindings,powershellFiles} from './automationHandoff'
import {armFixture} from './testing/armFixture'
import {exportFiles,diagramPages} from './exports'
import {commercialSummary} from './commercial'
import {collections,settings} from './catalog'
it('migrates schema 7 without selecting DSC or inventing resource contracts',()=>{const p=newProject(),old=structuredClone(p);old.schemaVersion=7;for(const g of settings){if((g.since??1)>7){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>7)delete old.config[g.key][f.key]}for(const g of collections)if((g.since??1)>7)delete old.records[g.key];expect(parseProject(canonical(old))).toEqual(p)})
it('keeps requested DSC versions and resources design-only with actionable contract findings',()=>{const p=newProject();p.config.automation.dsc='dsc-v3-design-handoff';const r=newRecord('dscResources');r.values.sourceCommit='main';r.values.parametersJson='{"x":1,"x":2}';p.records.dscResources=[r];expect(automationFindings(p).map(f=>f.field)).toEqual(expect.arrayContaining(['dsc','dscVersion','dscBoundary','sourceCommit','parametersJson']));expect(automationReview(p).dsc.executionReady).toBe(false);expect(Object.keys(powershellFiles(p)).some(path=>path.startsWith('adapters/dsc/'))).toBe(false);expect(sanitize(p).records.dscResources[0].values.sourceCommit).toBe('')})
it.each(['ad','local'] as const)('emits no PowerShell or DSC handoff for %s; ARM parameters are exported as data',async identity=>{const p=armFixture(identity),site=newRecord('sites');site.values.name='Synthetic handoff';p.records.sites.push(site);Object.assign(p.config.toolkit,{enabled:true,site:site.id,siteCode:'syn',environmentName:'synthetic',environmentType:'lab',boundary:'Local file conversion only'});p.records.nodes.forEach((n,i)=>{n.values.site=site.id;n.values.bmc=`203.0.113.${11+i}`});const files=await exportFiles(p,false,false);expect(Object.keys(powershellFiles(p))).toEqual(['plans/powershell-dsc-review.json']);expect(Object.keys(files).filter(path=>path.startsWith('adapters/'))).toEqual([]);expect(files['inputs/arm/azuredeploy.parameters.json']).toBeDefined();expect(automationReview(p).powershell.output).toBe('inputs/arm/azuredeploy.parameters.json')})
it('topology preserves edges to records outside the primary diagram',()=>{const p=newProject(),node=newRecord('nodes'),lun=newRecord('luns'),path=newRecord('ioPaths');path.values.node=node.id;path.values.lun=lun.id;p.records.nodes=[node];p.records.luns=[lun];p.records.ioPaths=[path];const page=diagramPages(p).find(x=>x.name==='Storage')!;expect(page.edges.some(x=>x.from===path.id&&x.to===node.id)).toBe(true);expect(page.nodes.find(x=>x.id===node.id)?.label).toContain('Reference: nodes')})
it('keeps currencies and unpriced assumptions separate from recurring quote arithmetic',()=>{const p=newProject();for(const [currency,period,unitPrice]of [['USD','monthly',10],['USD','annual',100],['EUR','one-time',30]] as const){const r=newRecord('licenses');Object.assign(r.values,{currency,period,unitPrice,quantity:2,priceReviewed:true,priceDate:'2026-09-11',priceSource:'Synthetic quote'});p.records.licenses.push(r)}p.records.licenses.push(newRecord('licenses'));const c=commercialSummary(p);expect(c.totals.find(x=>x.currency==='USD')?.annualRecurring).toBe(440);expect(c.totals.find(x=>x.currency==='EUR')?.oneTime).toBe(60);expect(c.unpriced).toHaveLength(1);expect(c.unresolvedRights).toHaveLength(4)})
