import {describe,it,expect} from 'vitest'
import {newProject,newRecord,canonical,parseProject,revise,sanitize} from './project'
import {executionHandoff,previewEvidence,retainEvidence,reconciliation,reconcileEvidence} from './evidence'
import {portRanges,addressRanges,networkFindings} from './networkRules'
import {portalMarkdown,portalSections} from './portal'
import {exportFiles,implementationMarkdown,pdf,schedules} from './exports'
describe('Operator handoff and safe reconciliation',()=>{
 it('retains exact receipt provenance before explicit adoption into a new revision',async()=>{const p=newProject(),r=executionHandoff(p).receiptTemplate;r.activityId='synthetic-activity';r.source='synthetic evidence';r.result='succeeded';r.observations=[{group:'project',record:'',field:'name',expected:'',observed:'Reviewed as built'}];const text=canonical(r),preview=await previewEvidence(text,p),saved=retainEvidence(p,preview);expect(saved.config.project.name).toBe('');expect(saved.evidence[0].verification).toBe('unverified');expect(saved.revision).toBe(p.revision+1);expect(()=>retainEvidence(saved,preview)).toThrow('changed');await expect(previewEvidence(text,{...p,id:'wrong-project'})).rejects.toThrow('match');const adopted=reconcileEvidence(saved,saved.evidence[0].id);expect(adopted.config.project.name).toBe('Reviewed as built');expect(adopted.evidence).toEqual(saved.evidence);expect(adopted.revision).toBe(saved.revision+1);expect(sanitize(adopted).evidence).toEqual([]);expect(()=>retainEvidence(saved,{...preview,snapshot:canonical(saved)})).toThrow('already');const files=await exportFiles(saved,false,false);expect(files['plans/external-execution.json']).toContain('"executionAuthorized": false');expect(implementationMarkdown(saved)).toContain('synthetic-activity');expect(schedules(saved).Evidence).toHaveLength(2);expect(pdf(saved,true).byteLength).toBeGreaterThan(1000)})
 it('rejects false qualification, mismatched types, secrets, bad stages and duplicate keys',async()=>{const p=newProject(),r=executionHandoff(p).receiptTemplate;for(const bad of [{...r,runtimeQualified:true},{...r,stageId:'not-a-stage'},{...r,projectRevision:99},{...r,observations:[{group:'sdn',record:'',field:'enabled',expected:true,observed:'false'}]},{...r,observations:[{group:'identity',record:'',field:'localAdmin',expected:'',observed:'keyvault://v/s'}]},{...r,source:'password=invalid-secret'}])await expect(previewEvidence(canonical(bad),p)).rejects.toThrow();await expect(previewEvidence(canonical(r).replace('"schemaVersion": 1','"schemaVersion": 1, "schemaVersion": 1'),p)).rejects.toThrow('Duplicate')})
 it('preserves running/failed observations and rejects stale or conflicting adoption',async()=>{const p=newProject(),r=executionHandoff(p).receiptTemplate;r.observations=[{group:'project',record:'',field:'name',expected:'old',observed:'found'}];let preview=await previewEvidence(canonical(r),p);expect(preview.changes[0].conflict).toBe(true);let saved=retainEvidence(p,preview);expect(()=>reconcileEvidence(saved,saved.evidence[0].id)).toThrow();r.observations[0].expected='';preview=await previewEvidence(canonical(r),p);saved=retainEvidence(p,preview);expect(reconciliation(saved,saved.evidence[0])?.terminal).toBe(false);expect(()=>reconcileEvidence(saved,saved.evidence[0].id)).toThrow();expect(()=>retainEvidence(revise(p),preview)).toThrow('changed')})
 it('rejects duplicate project keys and nested unsafe properties',()=>{const p=canonical(newProject());expect(()=>parseProject(p.replace('"sharing": false','"sharing": false, "sharing": true'))).toThrow('Duplicate');expect(()=>parseProject(p.replace('"config": {','"config": {"__proto__": {},'))).toThrow('Unsafe')})
})
describe('SDN rules and complete Portal worksheet',()=>{
 it('validates address and port grammar and documented SDN prefix/DNS mapping',()=>{expect(portRanges('0,443,1000-2000,*')).toHaveLength(4);for(const s of ['','65536','90-1','443x','-1'])expect(portRanges(s)).toBeNull();expect(addressRanges('10.0.0.0/24,10.1.1.1,*')).toHaveLength(3);for(const s of ['','10.0.0.999','example.test','10.0.0.0/33'])expect(addressRanges(s)).toBeNull();const p=newProject();p.config.sdn.prefix='too-long!';p.config.sdn.dnsRecord='wrong.test';expect(networkFindings(p).map(f=>f.field)).toEqual(expect.arrayContaining(['prefix','dnsRecord']));p.config.sdn.enabled=false;expect(networkFindings(p).some(f=>f.group==='sdn')).toBe(false)})
 it('finds opposite policy overlap and DHCP attachments with correction targets',()=>{const p=newProject(),nsg=newRecord('nsgs'),net=newRecord('logicalNetworks'),a=newRecord('rules'),b=newRecord('rules');Object.assign(a.values,{name:'allow',nsg:nsg.id,priority:100,source:'*',destination:'*',sourcePorts:'*',destinationPorts:'443',protocol:'tcp'});Object.assign(b.values,{...a.values,name:'deny',priority:200,action:'deny'});Object.assign(net.values,{nsg:nsg.id,mode:'dhcp'});p.records.nsgs=[nsg];p.records.rules=[a,b];p.records.logicalNetworks=[net];const f=networkFindings(p);expect(f.some(x=>x.record===b.id&&x.field==='priority'&&x.severity==='review')).toBe(true);expect(f.some(x=>x.record===net.id&&x.field==='mode')).toBe(true)})
 it('covers all Portal tabs, both identities, fixed layouts and SAN-specific requirements',()=>{for(const identity of ['ad','local'])for(const storage of ['s2d','san','hybrid']){const p=newProject();p.config.architecture.identity=identity;p.config.architecture.storage=storage;const text=portalMarkdown(p);expect(portalSections(p)).toHaveLength(11);for(const title of ['Basics','Configuration','Networking','Management','Security','Advanced','Tags','Validation','Review + create'])expect(text).toContain(title);expect(text).toContain('Resume deployment');if(storage==='san'){expect(text).toContain('disaggregated');expect(text).toContain('performance-history')}else expect(text).toContain('infrastructure volumes only');if(identity==='local')expect(text).toContain('No AD OU')}})
})
