import {canonical,parseProject,revise,sha256,uid,assertNoSecrets,MAX_FILE_BYTES,type Project,type EvidenceEntry} from './project'
import {collections,settings,type Value} from './catalog'
import {strictJson} from './strictJson'
export interface Observation {group:string;record:string;field:string;expected:Value;observed:Value}
export interface Receipt {kind:'azurelocal-external-receipt';schemaVersion:1;projectId:string;projectRevision:number;stageId:string;activityId:string;source:string;observedAt:string;result:'succeeded'|'failed'|'running';observations:Observation[]}
export interface EvidencePreview {snapshot:string;receipt:Receipt;hash:string;changes:{item:Observation;current:Value;conflict:boolean}[]}
function exact(o:unknown,keys:string[]):asserts o is Record<string,unknown>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).sort().join('|')!==keys.sort().join('|'))throw new Error('Receipt has missing or unknown fields')}
function location(p:Project,item:Pick<Observation,'group'|'record'|'field'>){const group=(item.record?collections:settings).find(g=>g.key===item.group),field=group?.fields.find(f=>f.key===item.field),values=item.record?p.records[item.group]?.find(r=>r.id===item.record)?.values:p.config[item.group];if(!field||!values)throw new Error('Observation target does not exist in this project');if(field.type==='secret')throw new Error('Secret references must be reviewed in the identity form, not reconciled from a receipt');return {field,values}}
export async function previewEvidence(text:string,p:Project):Promise<EvidencePreview>{
 if(new TextEncoder().encode(text).length>MAX_FILE_BYTES)throw new Error('Receipt exceeds the 4 MiB limit');assertNoSecrets(text)
 const raw=strictJson(text);exact(raw,['kind','schemaVersion','projectId','projectRevision','stageId','activityId','source','observedAt','result','observations'])
 if(raw.kind!=='azurelocal-external-receipt'||raw.schemaVersion!==1||raw.projectId!==p.id)throw new Error('Receipt kind, schema or project does not match')
 if(!Number.isSafeInteger(raw.projectRevision)||Number(raw.projectRevision)<1||Number(raw.projectRevision)>p.revision)throw new Error('Receipt revision must identify this or an earlier project revision')
 for(const key of ['stageId','activityId','source','observedAt'])if(typeof raw[key]!=='string'||!raw[key]||String(raw[key]).length>1000)throw new Error(`Receipt ${key} is required`)
 if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{3})?Z$/.test(String(raw.observedAt))||!Number.isFinite(Date.parse(String(raw.observedAt))))throw new Error('Receipt requires a UTC observation timestamp')
 if(!['succeeded','failed','running'].includes(String(raw.result)))throw new Error('Unknown terminal state')
 const stages=['foundation','identity','bootstrap','cluster','storage','sdn-prerequisites','sdn-enable','sdn-policy','workloads','handover',...p.records.stages.map(x=>x.id)];if(!stages.includes(String(raw.stageId)))throw new Error('Receipt stage is not in the execution handoff')
 if(!Array.isArray(raw.observations)||raw.observations.length>100)throw new Error('At most 100 observations per receipt are supported')
 const seen=new Set<string>();const changes=raw.observations.map(o=>{exact(o,['group','record','field','expected','observed']);for(const key of ['group','record','field'])if(typeof o[key]!=='string')throw new Error('Observation path must be text');const item=o as unknown as Observation,key=[item.group,item.record,item.field].join('/');if(seen.has(key))throw new Error('Duplicate observation target');seen.add(key);const {values}=location(p,item);if(typeof item.expected!==typeof values[item.field]||typeof item.observed!==typeof values[item.field])throw new Error('Observation type must match the field');const copy=structuredClone(p);location(copy,item).values[item.field]=item.observed;parseProject(canonical(copy));if(canonical(item).length>2500)throw new Error('Observation is too large for the evidence ledger');return {item,current:values[item.field],conflict:values[item.field]!==item.expected}})
 return {snapshot:canonical(p),receipt:raw as unknown as Receipt,hash:await sha256(text),changes}
}
export function retainEvidence(p:Project,preview:EvidencePreview):Project {if(canonical(p)!==preview.snapshot)throw new Error('Project changed after receipt preview. Import it again.');if(p.evidence.some(e=>e.sha256===preview.hash))throw new Error('This receipt is already retained');const next=structuredClone(p),r=preview.receipt;const entries=preview.changes.length?preview.changes.map(c=>({item:c.item,current:c.current})):[{item:null,current:''}];for(const {item,current}of entries){next.evidence.push({id:uid(),target:item?.record||p.id,kind:'external-receipt',source:r.source,observedAt:r.observedAt,projectRevision:r.projectRevision,expected:canonical(item?.expected??current),observed:canonical({stageId:r.stageId,activityId:r.activityId,result:r.result,item}),sha256:preview.hash,verification:'unverified'})}return parseProject(canonical(revise(next)))}
export function reconciliation(p:Project,e:EvidenceEntry){try{const data=strictJson(e.observed) as {item?:Observation;result?:string};if(!data.item)return null;const {values}=location(p,data.item);return {item:data.item,current:values[data.item.field],conflict:values[data.item.field]!==data.item.expected,terminal:data.result==='succeeded'}}catch{return null}}
export function reconcileEvidence(p:Project,id:string):Project {const entry=p.evidence.find(e=>e.id===id);if(!entry)throw new Error('Evidence entry not found');const change=reconciliation(p,entry);if(!change||change.conflict||!change.terminal)throw new Error('Only a successful, non-conflicting observation can be explicitly adopted');const next=structuredClone(p);location(next,change.item).values[change.item.field]=change.item.observed;return parseProject(canonical(revise(next)))}
export function executionHandoff(p:Project){return {kind:'azurelocal-external-execution-handoff',schemaVersion:1,projectId:p.id,projectRevision:p.revision,executionAuthorized:false,runtimeQualified:false,authorizationRequired:{approver:'',expiresAt:'',changeReference:'',allowedActions:[],exactTargets:[]},targets:collections.flatMap(g=>p.records[g.key].map(r=>({group:g.key,id:r.id,name:r.values.name??'',lifecycle:r.values.lifecycle??'design',existingId:r.values.existingId??'',resourceId:r.values.resourceId??r.values.arcResourceId??''}))),secrets:'Resolve references at runtime in the authorized controller. Never copy secret values into logs, receipts or project files.',resume:'Retain activity IDs and terminal results. Review failed/running stages and recovery instructions before authorizing resume. Imported evidence cannot authorize execution or mark a stage verified.',receiptTemplate:{kind:'azurelocal-external-receipt',schemaVersion:1,projectId:p.id,projectRevision:p.revision,stageId:'cluster',activityId:'REPLACE-WITH-ACTUAL-ACTIVITY-ID',source:'REPLACE-WITH-EVIDENCE-SOURCE',observedAt:p.updatedAt,result:'running',observations:[]} as Receipt}}
export function evidenceRows(p:Project){return p.evidence.map(e=>[e.target,e.kind,e.source,e.observedAt,e.projectRevision,e.expected,e.observed,e.sha256,e.verification])}
