import {useRef,useState} from 'react'
import {canonical,MAX_FILE_BYTES,type Project} from './project'
import {previewEvidence,retainEvidence,reconciliation,reconcileEvidence,executionHandoff,type EvidencePreview} from './evidence'
import {download} from './exports'
export function EvidencePanel({project,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const input=useRef<HTMLInputElement>(null),[preview,setPreview]=useState<EvidencePreview|null>(null),[message,setMessage]=useState('')
 const load=async(file?:File)=>{if(!file)return;try{if(file.size>MAX_FILE_BYTES)throw new Error('Receipt exceeds the 4 MiB limit');setPreview(await previewEvidence(await file.text(),project));setMessage('Review the reported outcome and differences. Importing preserves design intent.')}catch(e){setPreview(null);setMessage((e as Error).message)}finally{if(input.current)input.current.value=''}}
 return <section className="card" aria-label="Execution evidence and reconciliation"><h2>Execution evidence and reconciliation</h2><p>Keep externally reported results separate from design intent. A file hash checks integrity; it does not authenticate the operator or establish runtime qualification. Resume and infrastructure changes require separate target authorization.</p><div className="toolbar"><button onClick={()=>download('external-receipt-template.json',canonical(executionHandoff(project).receiptTemplate),'application/json')}>Download receipt template</button><button onClick={()=>input.current?.click()}>Import execution receipt</button><input ref={input} type="file" hidden accept=".json" onChange={e=>void load(e.target.files?.[0])}/></div><p aria-live="polite">{message}</p>
 {preview&&<div className="notice"><h3>Receipt preview</h3><p>Stage {preview.receipt.stageId} · reported {preview.receipt.result} · activity {preview.receipt.activityId} · revision {preview.receipt.projectRevision}</p><p>Source: {preview.receipt.source}. SHA-256: {preview.hash}</p>{preview.changes.map(c=><p key={`${c.item.group}/${c.item.record}/${c.item.field}`}><strong>{c.item.group}.{c.item.field}</strong>: current {String(c.current)} → reported {String(c.item.observed)}. {c.conflict?'Conflict: current intent differs from the receipt baseline.':'Baseline matches.'}</p>)}<button onClick={()=>{try{onChange(retainEvidence(project,preview));setPreview(null);setMessage('Receipt retained as unverified evidence. Design values are unchanged.')}catch(e){setMessage((e as Error).message)}}}>Retain receipt without changing intent</button><button onClick={()=>setPreview(null)}>Cancel receipt import</button></div>}
 {!project.evidence.length&&<p>No external evidence retained.</p>}{project.evidence.map(e=>{const change=reconciliation(project,e);return <details key={e.id}><summary>{e.kind} · {e.source} · {e.observedAt} · unverified</summary><p>Target {e.target}; reported against revision {e.projectRevision}.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{e.observed}</pre>{change&&<><p>Current intent: {String(change.current)}. Reported value: {String(change.item.observed)}.</p><p>{change.conflict?'Conflict: review this field manually; the receipt cannot overwrite later edits.':!change.terminal?'A running or failed receipt is retained for recovery review; it cannot be adopted.':'Adopting creates a new design revision and retains the original unverified receipt.'}</p><button disabled={change.conflict||!change.terminal||change.current===change.item.observed} onClick={()=>{try{onChange(reconcileEvidence(project,e.id));setMessage('Observed value explicitly adopted into a new design revision. Receipt remains unverified.')}catch(error){setMessage((error as Error).message)}}}>Adopt observed value into design</button></>}</details>})}</section>
}
