/** Section explanations and field help shown through the shared SectionIntro and "i" popups. Help is guidance only: it never changes validation, exports or schema. Keys must match catalog group and field keys; help.test.ts rejects orphans. */
import type {Group} from './catalog'

/** Explanations for configuration sections (one set of answers per project). */
export const settingIntros: Record<string, string> = {
  project: 'Who owns this design, what it is for and what already exists. The starting state and scope decide which later screens matter.',
  architecture: 'These choices switch whole sections on or off. Storage architecture, cluster identity, deployment route and SDN decide which questions later screens ask. Answers hidden by a change are kept, not deleted.',
  management: 'Decide whether management services are reused, deployed new, extended or customer-managed, and record what must not change.',
  bootstrap: 'How nodes and Azure are prepared before the cluster exists: who does the preparation, from where, and with which access. Runner, repository and permission questions appear only for an automated approach.',
  azure: 'The Azure tenant, subscription and resource group the instance registers into, with connectivity, policy and the cluster witness.',
  identity: 'Prepare Active Directory, or local identity with a cluster Key Vault, depending on the cluster identity choice. DNS and time apply to both.',
  security: 'Security settings applied at deployment. Keep the recommended profile unless the customer has an approved exception, and record every exception.',
  sdn: 'Azure Local SDN enabled by Arc runs Network Controller as a cluster service. Enablement is one-way, so record the owner, window and acceptance before selecting it.',
  capacity: 'Reserve and overcommit rules used to reconcile workload demand with node capacity on the Workloads screen.',
  arm: 'Values for the ARM parameter file. Shown when the deployment route is ARM or Terraform / Ansible. Secrets are bound to Key Vault references, never entered.',
  toolkit: 'Environment metadata for Toolkit hierarchy conversion data. Leave it off unless this design is being converted into the Toolkit.',
  automation: 'PowerShell version and optional DSC design requests for the handoff. Nothing here generates executable configuration.',
  hybrid: 'How the site connects privately to Azure. Answer used or not used for the site-to-site VPN, point-to-site VPN and ExpressRoute. Only the details for components in use are asked and exported.',
  outbound: 'How nodes reach Azure endpoints: direct, through a proxy, through an Arc gateway, both, or a private path. The Arc gateway cuts the firewall allow list to under 30 endpoints. HTTPS inspection is never supported.',
  firewall: 'The perimeter firewall. A TierPoint-managed FortiGate HA pair is part of the Azure Local hardware package. Choose a customer firewall to record its owner and gateways, or not used to hide these questions.',
  tor: 'The top-of-rack switch pair that carries management, compute and switched storage traffic. Dell PowerSwitch is the TierPoint default. Storage DCB questions appear only when storage is switched.',
  oob: 'Out-of-band access to BMCs and device consoles: a standard OOB switch, or an Opengear console manager enrolled in Lighthouse. Console port questions appear only for Opengear.',
  san: 'External SAN details for SAN and hybrid storage. Fibre Channel reveals fabric and zoning questions; iSCSI reveals path VLANs, subnets and portals. Requires Azure Local 2604 or later and is not rack-aware.',
  backup: 'Which backup solution protects the cluster and its workloads. Choose not used to hide these questions and leave backup out of the infrastructure data.',
  monitoring: 'Which monitoring the cluster uses. Azure Monitor Insights sends data to a Log Analytics workspace through a data collection rule. Choose not used to hide these questions.',
}

/** Explanations for record collections (one record per resource). */
export const recordIntros: Record<string, string> = {
  sites: 'Physical sites and racks. Nodes and management hosts reference these for placement and failure-domain review.',
  management: 'Each management service the platform needs, such as AD and DNS, gateways, monitoring, backup and runners: where it runs, who owns it and whether it must exist before the cluster.',
  dependencies: 'Startup, bootstrap and recovery ordering between services, tasks and stages. The implementation report orders prerequisites from these records.',
  bootstrapTasks: 'Preparation work done before the cluster exists: access, the deployment workstation, per-node preparation and removal of temporary resources.',
  azureResources: 'Azure resources the design creates or reuses, such as networks, Key Vaults, witness storage and policy. Record the existing resource ID when reusing.',
  identities: 'Accounts, groups and principals used by deployment and operations. Credentials are references only.',
  certificates: 'Certificates and trust chains with their renewal owners. Private keys are references only.',
  nodes: 'One record per physical machine: hardware, firmware, BMC, management address and readiness evidence.',
  media: 'OS images, drivers, firmware and packages with their source and expected SHA-256.',
  networks: 'Physical networks with role, VLAN, addressing, MTU and RDMA. Adapters, intents and switch configuration data reference these.',
  intents: 'Network ATC intents group adapters by traffic type. Record overrides only when the OEM or support requires them.',
  adapters: 'Every physical port on every node, the intent or SAN role it serves, and the switch port it connects to. Switch port configuration data comes from these records.',
  pools: 'The Storage Spaces Direct pool: repair reserve, fault domains and capacity alerting. Shown for S2D and hybrid storage.',
  devices: 'Local disks per node. Only eligible capacity and cache devices count toward the pool.',
  arrays: 'External SAN arrays with usable capacity after array protection. Shown for SAN and hybrid storage.',
  fabrics: 'Fibre Channel or iSCSI fabrics. Use one record per independent fabric so path diversity can be checked.',
  initiators: 'Host-side SAN identities: the WWPN or IQN on each node port, per fabric.',
  targets: 'Array-side SAN identities and portals, per controller and fabric.',
  luns: 'LUNs presented to the cluster, with masking, MPIO settings and the paths each node should see.',
  ioPaths: 'The expected path from each node through an initiator and target to a LUN, used to review redundancy.',
  volumes: 'Cluster Shared Volumes backed by the S2D pool or a SAN LUN, with size, resiliency and provisioning.',
  storagePaths: 'Azure storage paths map a directory on a CSV into Azure so Arc VMs and images can be placed there.',
  logicalNetworks: 'Networks that Arc VMs attach to: static, DHCP or SDN-backed, with address pools and an optional NSG.',
  nsgs: 'Network security groups for logical networks. Shown when SDN is enabled.',
  rules: 'Rules inside each network security group. Lower priority numbers are evaluated first.',
  workloads: 'Planned VMs, AVD, AKS and management workloads. Capacity review reconciles these with nodes, reserves and storage.',
  licenses: 'Licensing, subscriptions and support with quantities and price basis for the cost summary.',
  operations: 'Monitoring, backup, patching and handover requirements with owners and acceptance criteria.',
  stages: 'Ordered deployment and verification stages for the implementation report. Each stage is manual or handled by your existing automation; nothing runs from this tool.',
  lunPresentations: 'What each node actually sees for each LUN, used to confirm consistent presentation before cluster storage is created.',
  managementHosts: 'Platforms that host management services independently of the target cluster, with their spare capacity.',
  managementBindings: 'Links each management component to the Azure resources, identities or certificates it relies on.',
  accessChecks: 'Network and permission checks from each execution host to BMCs, DNS, Azure, repositories and proxies.',
  toolPins: 'Exact tool versions and sources the preparation relies on, so the handoff can be repeated.',
  bootstrapExits: 'How each temporary bootstrap service is replaced, handed over and removed.',
  armSecretBindings: 'Where each ARM secret parameter comes from: an existing Key Vault secret. Secret values are never entered here.',
  armStorageNetworks: 'Storage networks passed to the ARM template for S2D, with the operating-system adapter name used on each node.',
  storageAddresses: 'Static storage IP addresses per node, needed when Network ATC does not assign storage addresses automatically.',
  dnsZones: 'DNS zones and forwarders for local-identity clusters.',
  sbeProperties: 'Non-secret properties required by the OEM Solution Builder Extension (SBE).',
  sbeCredentials: 'Credentials the OEM Solution Builder Extension needs, recorded as references only.',
  firewalls: 'One record per firewall unit in the HA pair: hostname, HA role and addresses. Shown when the TierPoint-managed FortiGate is used.',
  torSwitches: 'One record per top-of-rack switch: hostname, pair role and addresses. Shown when top-of-rack switches are used.',
  nicLinks: 'Where each node port is cabled: the node port, the top-of-rack switch and its port, with the port mode and allowed VLANs.',
  firewallLinks: 'Where each firewall interface lands on a top-of-rack switch. Shown when both the TierPoint firewall and top-of-rack switches are used.',
  bmcLinks: 'Which out-of-band switch or Opengear port each node BMC (iDRAC) is cabled to.',
  storageLinks: 'Switchless cable map: one record per direct storage cable between two nodes. Two nodes need 1 (single) or 2 (dual) links, three nodes 3 or 6, four nodes 12 (dual only). Shown only for switchless storage.',
  consolePorts: 'Opengear serial ports and the device console each one connects to. Dell switches normally use 115200 baud; FortiGate consoles use 9600.',
}

/** Help for fields every record collection shares. */
export const commonRecordHelp: Record<string, string> = {
  lifecycle: 'new: create it. existing-preserve: document it and leave it unchanged. extend: add to it. external: owned outside this design. not-required: deliberately out of scope.',
  existingId: 'For an existing resource, the identity that never changes, such as an Azure resource ID, serial number or array ID. Leave blank for new resources.',
  evidence: 'Where the supporting evidence is kept, such as a ticket, document or file path. Never paste secrets.',
}

/** Field help for configuration sections, by section key then field key. */
export const settingHelp: Record<string, Record<string, string>> = {
  project: {
    environment: 'new-deployment: no hardware yet. existing-hardware: nodes exist without a cluster. existing-cluster: document or extend a running Azure Local instance.',
    scope: 'complete-platform covers management, cluster and workloads. cluster-only and management-only narrow the design. assessment documents without planning change.',
    preservation: 'For existing environments: what must not change, and which changes are allowed.',
    tags: 'Tags the customer requires on Azure resources, one per line as name=value.',
  },
  architecture: {
    release: 'The Azure Local release this design targets, as named in the release notes. Support, templates and SBE versions are checked against it.',
    osBuild: 'The exact OS build number published for the release.',
    sbeVersion: 'The OEM Solution Builder Extension version for the hardware, when the OEM provides one.',
    storage: 'S2D pools local disks across nodes. SAN uses an external array over Fibre Channel or iSCSI. Hybrid uses both with separate capacity budgets. Only the matching storage sections are shown.',
    identity: 'Active Directory joins nodes to a domain with a prepared OU. Local identity uses no domain and keeps credentials in a cluster Key Vault. Only the matching identity questions are shown.',
    topology: 'standard: nodes in one fault domain. rack-aware: nodes split across racks treated as separate fault domains. existing: an instance that is already deployed.',
    route: 'Portal produces a deployment worksheet. ARM produces an ARM parameter file. Terraform / Ansible produces tfvars and inventory data for your existing automation, plus the ARM parameter file. No automation code is produced.',
    depth: 'design-only: reports and schedules. operator-handoff: adds the implementation plan. automation-package: adds input data files for existing automation.',
    intent: 'new: deploy a new instance. reuse: use existing resources. extend: add to an existing instance. assess: document only. The ARM parameter file is produced only for new standard S2D designs.',
    networkPattern: 'converged: management, compute and storage share adapters. separated: storage uses dedicated adapters. custom: a reviewed layout outside these patterns.',
    switching: 'switched: storage runs through the top-of-rack pair. switchless: nodes cable directly to each other for storage. Microsoft supports switchless for 1 to 4 machines only, and 3 or 4 nodes deploy through ARM only. Hidden for SAN-only storage.',
    switchlessLinks: 'dual-link: two direct links between every pair of nodes. single-link: one link per pair. Four-node switchless is dual-link only. Record each cable in the switchless storage cable map on Host networking.',
    sanProtocol: 'Fibre Channel or iSCSI for the external SAN (Azure Local 2604 or later). The choice reveals the matching fabric, zoning or iSCSI path questions.',
    supportEvidence: 'Where the support review for this release, hardware and topology is recorded.',
  },
  management: {
    mode: 'Sets what the Management screen expects: reuse or extend existing services, deploy new ones, or leave them with the customer.',
    azurePlane: 'used: TierPoint management services such as DNS, network device monitoring, Lighthouse and Key Vaults run in Azure. not used hides these questions and the Azure resource bindings.',
    landingZone: 'simplified: a single management subscription. full-caf: the full Cloud Adoption Framework landing zone hierarchy.',
    hubCidr: 'The address space of the management hub VNet, for example 10.250.0.0/22. It must not overlap on-premises networks.',
    boundary: 'Which team owns each management service and what must not change.',
  },
  bootstrap: {
    mode: 'manual-operator: an engineer prepares the nodes. The automated approaches reveal runner, repository, authentication and permission questions.',
    ref: 'A tag or commit the preparation uses, so it can be repeated exactly.',
    runnerOS: 'Where your existing automation runs. Ansible needs an external Linux controller.',
    modulePins: 'Exact PowerShell module versions, one per line as name=version.',
    authentication: 'Prefer federated or managed identity. Federated and certificate options reveal their extra fields.',
    rbacScope: 'The narrowest Azure scope the runner needs, usually the resource group.',
    permissions: 'The roles the runner needs and how existing assignments were verified.',
    reachability: 'Confirmed access from the runner to node management addresses, BMCs, DNS and package sources.',
    proxyTrust: 'Proxy address, bypass list and any TLS inspection certificates the runner must trust.',
    exitPlan: 'How temporary access is removed after deployment, and who owns the services afterwards.',
    federationIssuer: 'The OIDC issuer URL of the pipeline system, for workload identity federation.',
    federationSubject: 'The subject claim the federated credential trusts, such as a specific project and branch.',
    federationAudience: 'The token audience, normally api://AzureADTokenExchange.',
    accessReview: 'operator-reported once someone has checked the permissions; unreviewed until then.',
  },
  azure: {
    cloud: 'The Azure environment. Commercial deployments use AzureCloud.',
    region: 'An Azure region that supports Azure Local registration, for example eastus.',
    tenant: 'The Entra tenant name or ID. This is a reference, not a secret.',
    subscription: 'The subscription name or ID the instance registers into.',
    resourceGroup: 'The resource group for the Azure Local instance and its Arc resources.',
    clusterName: 'The Azure resource name of the Azure Local instance.',
    customLocation: 'The custom location Arc VMs and AKS clusters deploy to. Created during deployment for a new instance.',
    resourceBridge: 'The Arc resource bridge. Created during deployment for a new instance; record the existing one when reusing.',
    providers: 'Resource providers that must be registered in the subscription, with evidence they are registered.',
    connectivity: 'Required outbound endpoints, proxy or private connectivity, and how they were validated.',
    witness: 'Cloud witness uses an Azure storage account; file-share uses an SMB share outside the cluster. Two-node and rack-aware clusters must have a cloud witness. none is only acceptable for five or more nodes.',
  },
  identity: {
    domain: 'The Active Directory domain FQDN the nodes join, for example corp.example.com.',
    ou: 'The OU prepared for this instance, as a distinguished name such as OU=AzL01,DC=corp,DC=example,DC=com.',
    delegation: 'How the OU was prepared and which permissions the deployment account holds on it.',
    localUser: 'The local administrator username that must be the same on every node.',
    vault: 'A Key Vault dedicated to this cluster. Local-identity clusters store their recovery secrets there.',
    vaultPermissions: 'The Azure Local resource provider permissions on the vault.',
    dnsNamespace: 'The DNS suffix the cluster and nodes register under.',
    dnsServers: 'DNS servers reachable from the management network, separated by commas.',
    timeSource: 'The NTP source for the nodes, such as the domain hierarchy or a named time server.',
    deploymentUser: 'The username of the AD account that runs the deployment. Its password is bound as a Key Vault reference.',
  },
  security: {
    profile: 'recommended applies the Azure Local security defaults. customized records deliberate changes. existing keeps the running configuration.',
    keyRecovery: 'Where BitLocker recovery keys are stored, as a reference.',
    exceptions: 'Each deviation from the recommended settings, with who approved it.',
    driftControlEnforced: 'Reapplies the security baseline periodically to correct drift.',
    credentialGuardEnforced: 'Protects credentials in memory with virtualization-based security.',
    smbSigningEnforced: 'Requires signed SMB traffic to and from the nodes.',
    smbClusterEncryption: 'Encrypts SMB traffic between cluster nodes, which adds CPU cost on storage traffic.',
    wdacEnforced: 'Enforces application control so only approved code runs on the nodes.',
    streamingDataClient: 'Sends operational telemetry to Microsoft.',
    euLocation: 'Stores telemetry in Microsoft EU data centers.',
    episodicDataUpload: 'Uploads diagnostic data when problems occur.',
  },
  sdn: {
    enabled: 'Turns on Azure Local SDN enabled by Arc. It cannot be turned off afterwards, and an existing on-premises Network Controller needs review first.',
    existingState: 'Any SDN already running on this environment. An on-premises Network Controller is never removed by this choice.',
    optOutReason: 'Why SDN stays off, so the decision is visible in the design review.',
    prefix: 'A short prefix used in SDN resource names.',
    dnsMode: 'static: you create the Network Controller DNS record. ad-dynamic: the record registers in Active Directory DNS.',
    reservedIp: 'An unused management-network IPv4 address kept for Network Controller.',
    irreversibleAcknowledged: 'Confirms the owner has reviewed that enablement is one-way.',
  },
  capacity: {
    failureReserveNodes: 'Nodes held back for failure and maintenance. Capacity review excludes them from usable capacity.',
    vcpuRatio: 'The vCPUs allowed per physical core. Higher ratios overcommit CPU, so confirm them against the workload profile.',
    osMemoryGiB: 'Memory kept on each node for the host operating system and services.',
    osCpu: 'vCPUs kept on each node for the host operating system and services.',
  },
  arm: {
    deploymentMode: 'Run Validate first. Deploy needs the ID of the successful validation below.',
    priorValidation: 'The deployment ID and result of the Validate run that this deployment follows.',
    managementNetwork: 'The physical network that carries infrastructure and node management addresses.',
    namingPrefix: 'The prefix for objects the template creates.',
    softDeleteRetentionDays: 'How long deleted Key Vault secrets can be recovered: 7 to 90 days.',
    configurationMode: 'Express creates infrastructure and workload volumes. InfraOnly creates infrastructure volumes only. KeepStorage keeps existing data volumes.',
    hciResourceProviderObjectId: 'The object ID of the Microsoft.AzureStackHCI resource provider service principal in the tenant.',
    enableStorageAutoIp: 'On: Network ATC assigns storage IP addresses. Off: record per-node addresses under Per-node storage addresses.',
    dnsServerConfig: 'UseDnsServer points nodes at existing DNS servers. UseForwarder uses local DNS that forwards to your servers.',
    sbeFamily: 'The SBE family from the OEM package manifest.',
    sbePublisher: 'The SBE publisher from the OEM package manifest.',
    sbeManifestSource: 'Where the OEM SBE manifest is published.',
    previewApiReviewed: 'Confirms the template API version, including any preview API, has been reviewed.',
    templateEffects: 'Resources the template creates or changes, and who reviewed them.',
  },
  toolkit: {
    enabled: 'Adds Toolkit hierarchy data and the ARM parameter file for conversion.',
    siteCode: 'The short site code used in Toolkit names.',
    environmentType: 'The Toolkit environment classification. Choose explicitly; it is never inferred.',
    tagsJson: 'A JSON object of Azure tags, for example {"environment":"poc"}.',
  },
  hybrid: {
    s2sVpn: 'used when the site connects to Azure over an IPsec tunnel, normally terminated on the FortiGate pair. not used hides the tunnel and BGP questions.',
    onPremPublicIp: 'The static public IPv4 or FQDN of the on-premises VPN device, used for the Azure local network gateway.',
    vpnGatewaySku: 'Zone-redundant AZ SKUs are recommended. Basic supports neither BGP, IKEv2 point-to-site nor RADIUS.',
    gatewaySubnet: 'The Azure subnet named GatewaySubnet: /27 or larger, with no NSG.',
    localAddressSpaces: 'On-premises prefixes Azure routes over the tunnel, separated by commas. Optional when BGP advertises them.',
    ipsecPolicy: 'default uses the Azure default proposals. custom requires every IKE and IPsec parameter, and matching settings on the firewall.',
    ikeProposal: 'For example aes256gcm-prfsha384 with DH group 14.',
    sharedKeyRef: 'A reference to the pre-shared key, for example keyvault://vault/vpn-shared-key. Never enter the key.',
    onPremAsn: 'A private ASN that differs from the Azure ASN. Azure reserves 8074, 8075, 12076 and 65515 to 65520.',
    azureAsn: 'Azure VPN gateways default to 65515.',
    onPremBgpPeerIp: 'The on-premises BGP peer address, often an APIPA address such as 169.254.21.1. It must not be the device public IP.',
    p2sVpn: 'used when administrators connect to Azure from their devices. not used hides the client pool and authentication questions.',
    p2sAddressPool: 'A private range that overlaps neither on-premises nor Azure. At least /29, or /28 for an active-active gateway.',
    p2sTunnel: 'OpenVPN is required for Entra ID authentication. SSTP is being retired.',
    p2sAuth: 'entra-id needs the OpenVPN tunnel. certificate needs an uploaded root certificate. radius needs RADIUS servers and a shared secret reference.',
    expressRoute: 'used when the site reaches Azure over an ExpressRoute circuit. not used hides the circuit and peering questions.',
    erPrimarySubnet: 'A /30 for the primary link that is not in any VNet. Your router takes the first usable address.',
    erPeerAsn: 'Your 2- or 4-byte ASN. Private ASNs are allowed except 65515 to 65520.',
    erGatewaySubnet: 'GatewaySubnet for the ExpressRoute gateway: /27 or larger, /26 for 16 circuits.',
  },
  outbound: {
    egressModel: 'direct: over 100 endpoints on the firewall. proxy: an enterprise proxy. arc-gateway: under 30 endpoints. proxy-arc-gateway: recommended for new production. private-path: ExpressRoute or VPN to Azure Firewall, 2608 or later.',
    proxyUrl: 'A non-authenticated proxy URL. PAC files and .local proxy hosts are not supported, and the proxy must be outside 10.96.0.0/12 and 10.244.0.0/16.',
    proxyBypass: 'Comma-separated: every machine IP and name, the cluster IP and name, and the infrastructure range. Wildcards are allowed; CIDR notation is not. It cannot change after deployment.',
    arcGatewayId: 'The Arc gateway resource ID in the deployment subscription. The gateway must exist before Arc registration.',
    privateFirewallIp: 'The private IPv4 of the Azure Firewall (Standard or Premium) explicit proxy. Every machine must reach it before registration.',
    endpointEvidence: 'Where the approved allow list and Environment Checker results are kept.',
  },
  firewall: {
    provider: 'tierpoint-fortinet: the TierPoint-managed FortiGate pair in the hardware package. customer: the customer firewall. not-used: hides these questions and leaves the firewall out of the infrastructure data.',
    model: 'FortiGate-30G for small edge sites, 90G for standard sites, 120G for high throughput.',
    haMode: 'TierPoint standard is an active-passive HA pair with session pickup.',
    gatewayVlans: 'Which VLAN default gateways live on the firewall, such as management, compute and OOB, one per line as VLAN=gateway.',
    dhcpScopes: 'DHCP scopes the firewall serves, one per line as VLAN=start-end. Exclude the Azure Local infrastructure pool.',
    vdomMode: 'no-vdom: one firewall context. multi-vdom: separate virtual domains, for example one per tenant.',
    credentialRef: 'A reference such as keyvault://vault/fortigate-admin. Never enter the password.',
    endpointApproach: 'How the customer allows Azure Local outbound endpoints: the full allow list, or an Arc gateway that reduces it.',
    httpsInspectionDisabled: 'Azure Local does not support HTTPS inspection anywhere on the outbound path.',
  },
  tor: {
    provider: 'tierpoint-dell: TierPoint-managed Dell PowerSwitch pair. customer: customer-owned switches. not-used: hides these questions; Azure Local still needs a switch for management and compute.',
    model: 'Check the model and OS version against the Microsoft validated switch list for Azure Local.',
    pairMode: 'vlt-pair: Dell VLT. mlag-pair: another vendor MLAG. single: one switch, for lab or single-node designs only.',
    peerLinkPorts: 'The VLTi or MLAG peer-link ports, for example ethernet1/1/13-1/1/14.',
    backupDestination: 'The peer switch out-of-band address used as the VLT backup link.',
    mtu: 'Switch ports normally use 9216 so host jumbo frames of 9014 pass end to end.',
    storageVlans: 'Storage VLAN IDs trunked to the nodes, separated by commas. Network ATC defaults to 711 and 712. RoCE needs non-zero VLANs.',
    rdmaType: 'RoCEv2 needs PFC and ETS on the switches. iWARP uses TCP and makes DCB optional.',
    pfcPriority: 'Network ATC uses priority 3 for SMB Direct. The switch must match the hosts.',
    etsSmbPercent: 'Network ATC reserves 50% for SMB Direct.',
    etsClusterPercent: 'Network ATC reserves 1% for cluster heartbeat on adapters faster than 10 Gbps, or 2% at 10 Gbps or less.',
  },
  oob: {
    model: 'opengear: an Opengear console manager with switch ports, enrolled in Lighthouse. oob-switch: a standard management switch. not-used: hides these questions.',
    vlan: 'The out-of-band VLAN for BMCs and device management ports.',
    gateway: 'The out-of-band gateway, normally on the firewall rather than the Opengear.',
    lighthouseAddress: 'The Lighthouse server IP or FQDN the Opengear enrolls with.',
    lighthousePort: 'Optional enrollment port. Lighthouse uses TCP 443 by default.',
    enrollmentTokenRef: 'A reference to the enrollment token, for example keyvault://vault/lighthouse-enrollment. Never enter the token.',
    enrollmentBundle: 'The Lighthouse enrollment bundle name, when a bundle-specific token is used.',
    internetUplink: 'The NET1 internet connection for Lighthouse, independent of the firewall: DHCP or static, and who provides it.',
    cellularFailover: 'Uses the cellular modem when the probe address is unreachable. Confirm the model has a modem.',
  },
  san: {
    arrayVendor: 'The array must be on the Microsoft supported list for Azure Local external SAN. Pure FlashArray is the TierPoint default.',
    zoningModel: 'TierPoint standard is single-initiator, single-target zones by WWPN. Zone HBAs into the array only after deployment.',
    iscsiVlanA: 'Each iSCSI path uses its own VLAN and subnet, with no default gateway on the iSCSI adapters.',
    iscsiMtu: 'The same MTU end to end on host, switch and array, for example 9014 on the host.',
    iscsiPortals: 'Target portal IPv4 addresses, separated by commas. TCP 3260 must reach every portal.',
  },
  backup: {
    solution: 'azure-backup: Azure Backup vault. mabs: Microsoft Azure Backup Server. third-party: another product. not-used: hides these questions.',
    mabsScope: 'host-level backs up whole VMs from every node. guest-level runs the agent inside VMs for application-consistent backup.',
    mabsAuth: 'Local-identity clusters are not domain joined and need certificate authentication.',
    dedicatedNetwork: 'A separate backup network, carried by a second compute intent or a backup vNIC.',
  },
  monitoring: {
    solution: 'azure-monitor: Azure Monitor Insights. tierpoint-noc: Azure Monitor with the TierPoint NOC alert catalog. customer-tool: another tool. not-used: hides these questions.',
    dataCollectionRule: 'Insights creates a rule prefixed AzureStackHCI-. Do not hand-build it.',
    deviceTelemetry: 'Sends firewall, switch and Opengear syslog and SNMP to the network device monitoring VM.',
  },
  automation: {
    dsc: 'Records DSC design requests only. No DSC configuration is generated.',
    dscBoundary: 'Which stage and targets a DSC request applies to, and what it must leave unchanged.',
  },
}

/** Field help for record collections, by collection key then field key. */
export const recordHelp: Record<string, Record<string, string>> = {
  management: {
    product: 'The kind of management service this record describes.',
    hosting: 'Where the service runs. A service on the target cluster cannot be required before that cluster exists.',
    requiredBeforeCluster: 'Services the deployment itself needs, such as AD, DNS or a runner, must run somewhere independent first.',
    execution: 'Installed manually or by your existing automation.',
    phase: 'A temporary bootstrap service needs a permanent replacement and an exit plan.',
    minimumAvailable: 'The number of instances that must keep running during a failure or maintenance.',
  },
  dependencies: {
    kind: 'startup and bootstrap set deployment order; recovery sets restore order.',
  },
  bootstrapTasks: {
    kind: 'node reveals BMC, boot, time and firmware preparation questions for that node.',
    handling: 'Done manually or by your existing automation. Nothing runs from this tool.',
  },
  azureResources: {
    resourceId: 'The full Azure resource ID for an existing resource.',
    parent: 'The resource this one belongs to, such as the virtual network for a subnet.',
  },
  identities: {
    kind: 'gMSA and managed identities avoid stored passwords where they are supported.',
    reuse: 'For an existing identity, how its current permissions were verified.',
  },
  nodes: {
    catalog: 'Evidence the model is listed in the Azure Local hardware catalog.',
    cores: 'Total physical cores across all sockets.',
    threadsPerCore: '2 with simultaneous multithreading enabled, otherwise 1.',
    bmc: 'The iDRAC, iLO or other BMC address.',
    arcId: 'The Arc machine resource ID after the node is registered.',
    readiness: 'Evidence the node passed hardware and Arc readiness checks.',
  },
  media: {
    expectedHash: 'The SHA-256 published by the source. The observed hash must match before use.',
  },
  networks: {
    role: 'What the network carries. Storage and iSCSI networks are normally non-routed.',
    routingScope: 'The routing domain this network belongs to, so overlapping address ranges can be detected.',
    vlan: 'Use 0 for untagged traffic.',
    reserved: 'Addresses inside the range that must not be assigned, separated by commas.',
    mtu: 'Must be supported end to end by adapters and switches. Jumbo frames are common on storage networks.',
    rdma: 'RoCE requires DCB with priority flow control on the switches. iWARP does not.',
    dcb: 'Priority flow control and ETS settings the switches must match.',
    switches: 'Which switches carry this network and how redundancy is provided.',
  },
  intents: {
    traffic: 'The traffic types sharing this intent. Adapters in one intent must be the same model and speed.',
    ownership: 'network-atc: Network ATC configures the adapters. existing-review: an existing configuration is kept and reviewed.',
    overrides: 'Only when the OEM or support requires changes to the Network ATC defaults.',
    bandwidthPercentageSmb: 'Network ATC reserves 50% for SMB by default.',
    priorityCluster: 'Network ATC uses priority 7 for cluster traffic by default.',
    prioritySmb: 'Network ATC uses priority 3 for SMB by default.',
  },
  adapters: {
    kind: 'nic for Ethernet ports; fc-hba for Fibre Channel host bus adapter ports.',
    port: 'The physical slot and port, for example Slot 3 Port 1.',
    ownership: 'network-atc for intent members, san-io for dedicated SAN ports, oob for management-only ports.',
    switchPort: 'The switch and port this cable lands on, for example tor-a Ethernet1/5. Switch port data is produced from this.',
    redundancyDomain: 'The switch or fabric failure domain this port connects to.',
    osName: 'The adapter name exactly as Windows shows it. The ARM template uses this name.',
  },
  pools: {
    reserveBytes: 'Capacity left unallocated so the pool can repair itself after a drive failure.',
    reserveMode: 'recommended calculates the repair reserve. explicit uses the value you enter.',
    faultDomains: 'Normally node. Rack-aware clusters use rack.',
    telemetryScope: 'planned-inventory counts only the CSVs listed here. observed-whole-source uses observed allocation for the whole pool.',
    alertPercent: 'Raise a capacity alert at this pool usage. The default is 70%.',
  },
  devices: {
    role: 'Capacity drives store data. Cache drives accelerate slower media. Boot drives are never pooled.',
    eligible: 'Confirmed the drive is empty, supported and not the boot device.',
  },
  arrays: {
    capacity: 'Usable capacity after the array\'s own RAID or protection, in the selected unit.',
    dataReduction: 'Deduplication and compression are recorded as evidence only and add no capacity.',
  },
  fabrics: {
    protocol: 'fc: Fibre Channel. iscsi: iSCSI over dedicated Ethernet.',
    zoning: 'The zoning approach, such as single-initiator zones, and when zones are created.',
  },
  initiators: {
    identity: 'The WWPN for Fibre Channel, such as 10:00:00:00:c9:12:34:56, or the IQN for iSCSI.',
    hostGroup: 'The array host group this node belongs to.',
    persistent: 'Confirmed iSCSI sessions reconnect automatically after a reboot.',
  },
  targets: {
    portal: 'The iSCSI target portal address. Leave blank for Fibre Channel.',
  },
  luns: {
    stableId: 'The array serial or NAA identifier that is identical on every node.',
    dsm: 'The MPIO device-specific module and version: Microsoft DSM or the array vendor\'s.',
    persona: 'The host type set on the array for Windows failover clusters.',
    expectedPaths: 'Paths each node should see. Two initiators and two targets usually give four.',
    existingData: 'LUNs with existing data are kept, never reformatted by the design.',
  },
  ioPaths: {
    observedState: 'Stays unverified until an operator records what the node sees.',
  },
  volumes: {
    source: 's2d uses the pool. san uses the LUN selected below.',
    provisioning: 'Thin volumes allocate on write, so set a growth reserve and alert policy.',
    resiliency: 'Three-way mirror suits three or more nodes, two-way or nested mirror suits two. Parity trades performance for capacity.',
    filesystem: 'ReFS is recommended for Cluster Shared Volumes.',
    mount: 'The CSV path under C:\\ClusterStorage.',
  },
  storagePaths: {
    directory: 'A directory on the backing CSV, such as C:\\ClusterStorage\\UserStorage_1\\vms.',
  },
  logicalNetworks: {
    mode: 'static assigns addresses from the pool below. dhcp uses an existing DHCP server. sdn-static uses static addressing with SDN policy.',
    nsg: 'An optional network security group. Requires SDN.',
  },
  rules: {
    priority: 'Lower numbers are evaluated first.',
  },
  workloads: {
    computeAccounting: 'aks-worker-capacity counts this record as capacity for AKS workers instead of extra demand.',
    cpuDemandRatio: 'Divides vCPU demand for workloads that do not use all their vCPUs. 1 counts every vCPU.',
    externalStorageGiB: 'Storage this workload uses outside the target cluster, which is not counted against it.',
    hosting: 'external workloads are documented but not counted against cluster capacity.',
    vhdx: 'Fixed disks allocate their full size up front. Dynamic disks grow on use.',
    storageAccounting: 'included-in-parent avoids counting storage twice when another workload already includes it.',
  },
  licenses: {
    acquisition: 'existing: already owned. purchase: must be bought. included: part of another agreement.',
  },
  stages: {
    handling: 'Done manually or by your existing automation. No stage runs from this tool.',
    consumer: 'The automation that performs this stage and its version.',
    observation: 'Status reported by the operator. It never changes the design itself.',
  },
  lunPresentations: {
    sectorBytes: 'The logical sector size the node reports: 512 or 4096.',
  },
  managementHosts: {
    capacityBasis: 'planned uses expected capacity. operator-observed uses capacity someone has measured.',
  },
  accessChecks: {
    requiredScope: 'The least access that satisfies this check.',
  },
  armSecretBindings: {
    secretVersion: 'Pin a version so repeat deployments use the same secret.',
  },
  armStorageNetworks: {
    adapterName: 'The storage adapter name exactly as Windows shows it on every node.',
  },
  firewalls: {
    role: 'primary is the active unit; secondary is the standby unit in an active-passive pair.',
    oobIp: 'The firewall address on the out-of-band network.',
    haPriority: 'Higher priority wins the primary role, for example 200 on the primary.',
    heartbeatPorts: 'The HA heartbeat interfaces, cross-connected between the units.',
  },
  torSwitches: {
    role: 'primary and secondary members of the VLT or MLAG pair, or standalone.',
    vltPriority: 'Lower VLT priority becomes the primary peer.',
    credentialRef: 'A reference such as keyvault://vault/switch-admin. Never enter the password.',
  },
  nicLinks: {
    adapter: 'The node physical port from Physical ports and adapters.',
    torPort: 'The switch interface, for example ethernet1/1/3.',
    vlans: 'VLANs allowed on a trunk port, or the access VLAN, separated by commas.',
  },
  firewallLinks: {
    firewallPort: 'The firewall interface, for example wan2 or port4.',
  },
  bmcLinks: {
    oobPort: 'The OOB switch or Opengear switch port, for example SW3.',
  },
  storageLinks: {
    linkIndex: 'The number of this link in the full mesh, from 1 to the number of links the pattern needs.',
    nodeA: 'One end of the direct cable.',
    portA: 'The storage port on node A, from Physical ports and adapters. Each storage port carries one link only.',
    nodeB: 'The other end of the direct cable. It must be a different node from node A.',
    portB: 'The storage port on node B, from Physical ports and adapters. Each storage port carries one link only.',
    subnet: 'Each link uses its own storage subnet, for example 10.71.1.0/24. Three- and four-node switchless needs every storage IP defined.',
    vlan: 'The storage VLAN on this link. Three- and four-node patterns use one VLAN for all storage subnets, for example 711.',
  },
  consolePorts: {
    device: 'The firewall, switch or node whose console is cabled to this port.',
    deviceLabel: 'Use when the connected device has no record in this design.',
    pinout: 'Cisco rolled suits most Dell and Fortinet console cables.',
  },
}

/** Adds help to catalog groups without replacing help already defined in the catalog. */
export function applyHelp(settings: Group[], collections: Group[]) {
  for (const group of settings) {
    group.help ??= settingIntros[group.key]
    for (const field of group.fields) field.help ??= settingHelp[group.key]?.[field.key]
  }
  for (const group of collections) {
    group.help ??= recordIntros[group.key]
    for (const field of group.fields) field.help ??= recordHelp[group.key]?.[field.key] ?? commonRecordHelp[field.key]
  }
}
