import type {Project} from './project'
import type {Finding} from './assessment'
import {activeRecords} from './selectors'
import {ipv4,subnet} from './networkMath'
export const dnsName=(v:string)=>v.length<=253&&v.split('.').every(s=>/^[a-z\d](?:[a-z\d-]{0,61}[a-z\d])?$/i.test(s))
const tokens=(v:unknown)=>String(v).trim().split(/[\s,]+/).filter(Boolean)
export function portRanges(v:unknown):[number,number][]|null {const list=tokens(v);if(!list.length)return null;const out:[number,number][]=[];for(const s of list){if(s==='*'){out.push([0,65535]);continue}if(!/^\d{1,5}(?:-\d{1,5})?$/.test(s))return null;const [a,b=a]=s.split('-').map(Number);if(a>b||b>65535)return null;out.push([a,b])}return out}
export function addressRanges(v:unknown):[number,number][]|null {const list=tokens(v);if(!list.length)return null;const out:[number,number][]=[];for(const s of list){if(s==='*'){out.push([0,2**32-1]);continue}const ip=ipv4(s),net=subnet(s);if(ip!==null)out.push([ip,ip]);else if(net)out.push([net.start,net.end]);else return null}return out}
const overlap=(a:[number,number][]|null,b:[number,number][]|null)=>!!a&&!!b&&a.some(x=>b.some(y=>x[0]<=y[1]&&y[0]<=x[1]))
export function networkFindings(p:Project):Finding[]{const out:Finding[]=[];const add=(group:string,record:string,field:string,message:string,resolution:string,severity:Finding['severity']='error')=>out.push({id:`network:${group}:${record}:${field}:${out.length}`,group,record,field,screen:group==='identity'?5:10,severity,category:'input',message,resolution});const s=p.config.sdn
 if(s.enabled){if(!/^[A-Za-z0-9]{1,8}$/.test(String(s.prefix)))add('sdn','','prefix','SDN prefix must contain 1–8 letters or digits.','Use the prefix that will form the Network Controller DNS name.');if(s.dnsMode==='static'&&s.dnsRecord){const name=String(s.dnsRecord);if(!dnsName(name)||name.split('.')[0].toLowerCase()!==`${s.prefix}-nc`.toLowerCase())add('sdn','','dnsRecord','The static DNS record must use the selected prefix followed by -NC.','Enter prefix-NC or its fully qualified DNS name and verify its reserved address.')}}
 for(const key of ['dnsNamespace',...(p.config.architecture.identity==='ad'?['domain']:[])])if(p.config.identity[key]&&!dnsName(String(p.config.identity[key])))add('identity','',key,'Invalid DNS name.','Use dot-separated DNS labels without spaces or leading/trailing hyphens.')
 if(p.config.identity.dnsServers&&tokens(p.config.identity.dnsServers).some(x=>ipv4(x)===null))add('identity','','dnsServers','DNS server addresses must be valid IPv4 addresses.','Separate the selected servers with commas or spaces.')
 for(const n of activeRecords(p,'logicalNetworks'))if(n.values.nsg&&n.values.mode==='dhcp')add('logicalNetworks',n.id,'mode','An NSG requires a static logical network.','Choose a supported static network or remove the NSG attachment.')
 const rules=activeRecords(p,'rules');for(const r of rules){for(const key of ['source','destination'])if(!addressRanges(r.values[key]))add('rules',r.id,key,'Invalid or missing address selector.','Use * or IPv4 addresses/CIDRs, separated by commas. Other address families require a separate consumer review.');for(const key of ['sourcePorts','destinationPorts'])if(!portRanges(r.values[key]))add('rules',r.id,key,'Invalid or missing port selector.','Use *, a port from 0–65535, or an ascending range such as 443-445.');if(r.values.protocol==='icmp'&&(r.values.sourcePorts!=='*'||r.values.destinationPorts!=='*'))add('rules',r.id,'protocol','ICMP does not select TCP/UDP ports.','Use * for both port fields.');for(const other of rules.filter(x=>x.id!==r.id&&x.values.nsg===r.values.nsg)){if(String(other.values.name).toLowerCase()===String(r.values.name).toLowerCase())add('rules',r.id,'name','Rule names must be unique within an NSG.','Choose a distinct name.');if(other.values.direction===r.values.direction&&Number(other.values.priority)<Number(r.values.priority)&&(other.values.protocol==='any'||r.values.protocol==='any'||other.values.protocol===r.values.protocol)&&['source','destination'].every(k=>overlap(addressRanges(other.values[k]),addressRanges(r.values[k])))&&['sourcePorts','destinationPorts'].every(k=>overlap(portRanges(other.values[k]),portRanges(r.values[k])))&&other.values.action!==r.values.action)add('rules',r.id,'priority',`Traffic overlaps the earlier rule ${other.values.name}.`,'Review order and address/port selectors against intended allow/deny traffic.','review')}}
 for(const nsg of activeRecords(p,'nsgs')){if(!rules.some(r=>r.values.nsg===nsg.id))add('nsgs',nsg.id,'name','An empty NSG denies inbound traffic.','Add reviewed rules before attaching this NSG.');if(!nsg.values.managementAccess)add('nsgs',nsg.id,'managementAccess','Management access acceptance is missing.','Record the management source, required ports and positive/negative traffic checks.','review')}
 return out
}
