import type {Project} from './project'
import {settings,collections,fieldApplicable} from './catalog'
import {activeRecords} from './selectors'
const esc=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\|/g,'\\|').replace(/\r?\n/g,'<br>')
export const portalInputKeys=['keyVault','softDeleteRetentionDays','customLocationName','configurationMode','storageHandling','enableStorageAutoIp','localAdminUsername','localAdminSecret']
export function portalSections(p:Project){const san=p.config.architecture.storage==='san',hybrid=p.config.architecture.storage==='hybrid',local=p.config.architecture.identity==='local';return [
 {title:'Prerequisites',notes:'Confirm the selected release, qualified hardware, Arc registration, deployment permissions and independent management. Reuse/extend designs require an approved change boundary before opening a new-cluster wizard.',config:['project','architecture'],records:['nodes','media','management','bootstrapTasks']},
 {title:'1. Basics',notes:`Select subscription, resource group, instance, region, topology and ${local?'Local identity with Key Vault':'Active Directory'} identity. Add the exact Arc machines, install extensions and wait for machine validation. ${san?'Select SAN storage and standard topology; rack-aware is unavailable.':'Select the qualified S2D topology.'} Select a new or existing eligible Key Vault; an existing vault with private endpoints is unsupported for deployment.`,config:['azure'],records:['azureResources']},
 {title:'2. Configuration',notes:'Choose New configuration or an explicitly reviewed Template spec. The Quickstart template option is unavailable in the documented Portal flow. This worksheet supplies values; it does not upload a template spec.',config:[],records:[]},
 {title:'3. Networking',notes:san?'Use the SAN networking branch, with management/compute grouping. Keep fabric and SAN I/O ownership separate. Resolve the FC/iSCSI documentation conflict against the selected SAN release before execution.':'Select switched/switchless and the supported traffic grouping. Match exact physical adapter names, VLANs and reviewed overrides. Portal uses Network ATC storage IP assignment; custom storage IPs require ARM. Reserve the infrastructure pool separately from host addresses.',config:[],records:['networks','intents','adapters','armStorageNetworks','storageAddresses']},
 {title:'4. Management',notes:local?'Review custom location, witness and local administrator reference. Prepare DNS zones/forwarders, ownership and cluster-specific Key Vault permissions/recovery. No AD OU or domain deployment account is required for this identity branch.':'Review custom location and witness. Enter the prepared domain FQDN, OU, deployment user and identical node-local administrator credentials resolved privately at runtime. The OU must not be the domain root.',config:['identity'],records:['identities','dnsZones','certificates']},
 {title:'5. Security',notes:'Review recommended or customized security settings, encryption/key recovery, credential protection, drift control, application control and telemetry. Record exceptions and owner approval.',config:['security'],records:[]},
 {title:'6. Advanced',notes:san?'Review the infrastructure and performance-history LUN roles, consistent presentation, stable identities and preservation boundary. Array provisioning, CSV allocation and VHDX allocation remain separate.':`The Portal automatic workload option creates thin volumes. To retain fixed or mixed explicit CSV layouts, select infrastructure volumes only and create the reviewed workload layout after deployment. KeepStorage applies only to an eligible single-machine existing pool and requires preservation review.${hybrid?' Attach the external SAN after the S2D cluster is deployed; hybrid attachment does not qualify SAN-only deployment.':''}`,config:[],records:san?['arrays','fabrics','initiators','targets','luns','ioPaths','volumes','storagePaths']:['pools','volumes','storagePaths',...(hybrid?['arrays','luns','ioPaths']:[])]},
 {title:'7. Tags',notes:'Review project tags and customer ownership. Tags in this worksheet are user-supplied design values.',config:[],records:[]},
 {title:'8. Validation',notes:'Run the actual Portal validation only against separately authorized targets. Resolve failures and retain deployment/activity IDs and terminal results. Configurator checks do not substitute for environment validation.',config:[],records:[]},
 {title:'9. Review + create',notes:'Recheck target identities, preservation boundaries, cost and ownership before the authorized operator starts deployment. Wait for terminal completion, then verify resources and cluster health.',config:[],records:[]},
 {title:'Post-deployment and recovery',notes:`Verify Arc machines, Azure Local, resource bridge, custom location, infrastructure logical network, vault/witness and selected storage paths. ${p.config.sdn.enabled?'Complete the separately gated Arc SDN prerequisites, enablement, terminal action-plan and traffic acceptance.':'Arc SDN opt-out omits enablement and policy stages.'} A failed deployment is reviewed through the instance Deployments > Resume deployment workflow; retain the original activity and recovery context. Complete monitoring, restore tests and handover.`,config:['sdn'],records:['operations','stages']},
 ]}
export function portalMarkdown(p:Project){const san=p.config.architecture.storage==='san';const document=san?'deploy-via-portal-disaggregated':'deploy-via-portal';return ['# Azure portal deployment worksheet','',`Project ${esc(p.config.project.name)} · revision ${p.revision} · release ${esc(p.config.architecture.release)}`,'','Qualification: documentation-mapped operator handoff; no live deployment qualification. The selected support findings still apply.',`Source: https://learn.microsoft.com/en-us/azure/azure-local/deploy/${document}?view=azloc-2604`,'Source revision for the common Portal flow: MicrosoftDocs/azure-stack-docs c320ca069a5e1f5137a0b6c6ff934c984ece08de; disaggregated flow additionally reviewed 2026-09-11.','','## Selected Portal inputs','| Field | Value |','| --- | --- |',...settings.find(g=>g.key==='arm')!.fields.filter(f=>portalInputKeys.includes(f.key)&&fieldApplicable(f,p.config.arm,p.config)).map(f=>'| '+esc(f.label)+' | '+esc(p.config.arm[f.key])+' |'),' ',...portalSections(p).flatMap(section=>[`## ${section.title}`,section.notes,'',...(section.title==='7. Tags'?[`Tags: ${esc(p.config.toolkit.tagsJson)}`]:[]),...section.config.flatMap(key=>{const g=settings.find(x=>x.key===key)!;return ['| Field | Value |','| --- | --- |',...g.fields.filter(f=>fieldApplicable(f,p.config[key],p.config)).map(f=>`| ${esc(f.label)} | ${esc(p.config[key][f.key])} |`),'']}),...section.records.flatMap(key=>{const g=collections.find(x=>x.key===key)!;return activeRecords(p,key).flatMap(r=>[`### ${esc(g.title)}: ${esc(r.values.name||r.id)}`,'| Field | Value |','| --- | --- |',...g.fields.filter(f=>fieldApplicable(f,r.values,p.config)).map(f=>`| ${esc(f.label)} | ${esc(r.values[f.key])} |`),''])})])].join('\n')}
