import {describe,it,expect} from 'vitest'
import {collections,settings,fieldApplicable} from './catalog'
import {newProject,newRecord,parseProject,canonical,sanitize} from './project'
import {managementCapacity,preparationGraph,preparationPlan} from './preparation'
import {preparationFindings,validTimestamp,exactVersion} from './preparationRules'
import {assess} from './assessment'
import {exportFiles,implementationMarkdown,designMarkdown,schedules} from './exports'

function fixture(){const p=newProject(),host=newRecord('managementHosts'),service=newRecord('management');Object.assign(host.values,{name:'Independent host',platform:'independent-hypervisor',availableCpu:16,availableMemoryGiB:64,availableDiskGiB:1000,availableBeforeCluster:true});Object.assign(service.values,{name:'Utility service',product:'utility-jump',hosting:'independent-hypervisor',hostingResource:host.id,count:2,cpu:4,memoryGiB:8,diskGiB:100});p.records.managementHosts=[host];p.records.management=[service];p.config.bootstrap.runnerHost=host.id;return {p,host,service}}
describe('management and bootstrap prerequisites',()=>{
 it('resolves certificate, tool and access prerequisites to real graph resources',()=>{const {p,host,service}=fixture(),certificate=newRecord('certificates'),pin=newRecord('toolPins'),check=newRecord('accessChecks');service.values.certificate=certificate.id;p.records.certificates=[certificate];pin.values.executor=host.id;check.values.executor=host.id;p.records.toolPins=[pin];p.records.accessChecks=[check];const graph=preparationGraph(p);expect(graph.missing).toEqual([]);expect(graph.edges).toEqual(expect.arrayContaining([expect.objectContaining({from:service.id,to:certificate.id}),expect.objectContaining({from:'system:bootstrap',to:pin.id}),expect.objectContaining({from:'system:bootstrap',to:check.id})]));check.values.executor='missing-host';expect(preparationGraph(p).blocked).toContain('system:bootstrap')})
 it('calculates independent hosting demand and preserves target-cluster budgets',()=>{const {p,host,service}=fixture();host.values.reservedCpu=2;host.values.reservedMemoryGiB=8;host.values.reservedDiskGiB=100;expect(managementCapacity(p)[0]).toMatchObject({cpu:8,memoryGiB:16,diskGiB:200,availableCpu:14,availableMemoryGiB:56,availableDiskGiB:900,runtimeQualified:false});service.values.count=10;expect(preparationFindings(p).filter(f=>f.record===host.id&&f.category==='capacity')).toHaveLength(3)})
 it('accounts explicitly sized operations services and excludes external service commitments',()=>{const {p,service}=fixture();service.values.product='monitoring';expect(managementCapacity(p)[0].cpu).toBe(8);service.values.hosting='external';expect(managementCapacity(p)[0].cpu).toBe(0)})
 it('detects indirect bootstrap cycles through a target-hosted service identity and resource dependency',()=>{const {p,service}=fixture();service.values.product='runner';service.values.hosting='target-cluster';service.values.hostingResource='';p.config.bootstrap.runnerComponent=service.id;p.config.bootstrap.mode='existing-automation';const graph=preparationGraph(p);expect(graph.blocked).toEqual(expect.arrayContaining(['system:cluster','system:bootstrap',service.id]));expect(preparationFindings(p).some(f=>f.group==='bootstrap'&&f.message.includes('cannot become available'))).toBe(true);service.values.hosting='independent-hypervisor';service.values.hostingResource=p.records.managementHosts[0].id;expect(preparationGraph(p).blocked).toEqual([])})
 it('orders host, service, bootstrap and cluster without treating replacement as a startup prerequisite',()=>{const {p,host,service}=fixture();service.values.requiredBeforeCluster=true;service.values.phase='temporary-bootstrap';const final=newRecord('management');Object.assign(final.values,{phase:'permanent',hosting:'target-cluster'});p.records.management.push(final);service.values.finalComponent=final.id;p.config.bootstrap.runnerComponent=service.id;p.config.bootstrap.mode='existing-automation';const graph=preparationGraph(p),wave=(id:string)=>graph.waves.findIndex(w=>w.includes(id));expect(graph.blocked).toEqual([]);expect(wave(host.id)).toBeLessThan(wave(service.id));expect(wave(service.id)).toBeLessThan(wave('system:bootstrap'));expect(wave('system:bootstrap')).toBeLessThan(wave('system:cluster'));expect(wave('system:cluster')).toBeLessThan(wave(final.id))})
 it('blocks missing prerequisites without silently treating them as external success',()=>{const {p,service}=fixture();service.values.serviceIdentity='missing-identity';const graph=preparationGraph(p);expect(graph.missing.some(e=>e.to==='missing-identity')).toBe(true);expect(graph.blocked).toContain(service.id);expect(assess(p).some(f=>f.record===service.id&&f.field==='serviceIdentity')).toBe(true)})
 it('requires matching independent hosting, predeployment availability and surviving instances',()=>{const {p,host,service}=fixture();service.values.minimumAvailable=2;service.values.reservedFailureInstances=1;service.values.requiredBeforeCluster=true;host.values.availableBeforeCluster=false;host.values.platform='physical';const fields=preparationFindings(p).filter(f=>f.record===service.id).map(f=>f.field);expect(fields).toEqual(expect.arrayContaining(['minimumAvailable','failureDomains','hostingResource']))})
 it('keeps WAC estate scope explicit and does not force AD for a local-identity cluster',()=>{const {p,service}=fixture();p.config.architecture.identity='local';service.values.product='wac';expect(preparationFindings(p).some(f=>f.field==='targetEstate'&&f.severity==='error')).toBe(true);service.values.targetEstate='independent-estate';expect(assess(p).some(f=>f.record===service.id&&f.message.includes('WAC cannot'))).toBe(false);service.values.product='ad-dns';expect(assess(p).some(f=>f.record===service.id&&f.category==='support')).toBe(false);expect(preparationFindings(p).some(f=>f.field==='replicationOwner')).toBe(true)})
 it('keeps OME manual and requires a separate acceptance handoff',()=>{const {p,service}=fixture();service.values.product='ome';service.values.execution='external-automation';expect(assess(p).some(f=>f.record===service.id&&f.field==='execution')).toBe(true);expect(preparationFindings(p).some(f=>f.field==='manualHandoff')).toBe(true)})
 it('validates resource-purpose bindings and inferred edges',()=>{const {p,service}=fixture(),resource=newRecord('azureResources'),binding=newRecord('managementBindings');resource.values.kind='vnet';Object.assign(binding.values,{component:service.id,role:'subnet',resource:resource.id});p.records.azureResources=[resource];p.records.managementBindings=[binding];expect(preparationFindings(p).some(f=>f.group==='managementBindings'&&f.field==='resource')).toBe(true);binding.values.role='vnet';expect(preparationFindings(p).some(f=>f.group==='managementBindings')).toBe(false);expect(preparationGraph(p).edges.some(e=>e.from===service.id&&e.to===resource.id)).toBe(true)})
 it('requires dated permission reuse and complete federation without deleting an identity',()=>{const {p}=fixture(),identity=newRecord('identities');Object.assign(identity.values,{lifecycle:'existing-preserve',existingId:'stable-principal',kind:'service-principal'});p.records.identities=[identity];Object.assign(p.config.bootstrap,{mode:'existing-automation',serviceIdentity:identity.id,authentication:'federated',accessReview:'operator-reported',permissionReviewAt:'2026-02-30T10:00:00Z'});const before=canonical(p),issues=preparationFindings(p);expect(issues.some(f=>f.field==='reuse'&&f.category==='preservation')).toBe(true);expect(issues.some(f=>f.field==='accessReview')).toBe(true);expect(issues.some(f=>f.field==='federationIssuer')).toBe(true);expect(canonical(p)).toBe(before)})
 it('keeps manual preparation independent of CI/CD identity enrollment',()=>{const {p}=fixture();p.config.bootstrap.mode='manual-operator';expect(preparationFindings(p).some(f=>f.group==='bootstrap'&&['repository','serviceIdentity','runnerPool','consentOwner'].includes(f.field))).toBe(false);expect(preparationFindings(p).some(f=>f.field==='powershellVersion')).toBe(true)})
 it('validates exact tool versions and unverified access observations',()=>{const {p,host}=fixture(),pin=newRecord('toolPins'),check=newRecord('accessChecks');Object.assign(pin.values,{executor:host.id,kind:'powershell',version:'^7.5.0',sha256:'bad'});Object.assign(check.values,{executor:host.id,observation:'unreachable',observedAt:'yesterday'});p.records.toolPins=[pin];p.records.accessChecks=[check];const issues=preparationFindings(p);expect(issues.some(f=>f.record===pin.id&&f.field==='version')).toBe(true);expect(issues.some(f=>f.record===pin.id&&f.field==='sha256')).toBe(true);expect(issues.some(f=>f.record===check.id&&f.field==='observedAt')).toBe(true);expect(issues.some(f=>f.record===check.id&&f.field==='target')).toBe(true);expect(preparationPlan(p).accessChecks[0]).toMatchObject({observation:'unreachable'});expect(validTimestamp('2026-09-11T10:00:00Z')).toBe(true);expect(validTimestamp('2026-02-30T10:00:00Z')).toBe(false);expect(exactVersion('7.5.3')).toBe(true);expect(exactVersion('latest')).toBe(false)})
 it('requires per-node media, initial account and firmware/Arc acceptance without copying credentials',()=>{const {p}=fixture(),task=newRecord('bootstrapTasks');task.values.kind='node';p.records.bootstrapTasks=[task];const fields=preparationFindings(p).filter(f=>f.record===task.id).map(f=>f.field);expect(fields).toEqual(expect.arrayContaining(['node','media','credential','executorHost','bmcMethod','timeDns','firmwareAcceptance','arcAcceptance']));task.values.credential='actual-password';expect(()=>parseProject(canonical(p))).toThrow('secret-ref://')})
 it('requires distinct temporary/permanent records and full exit acceptance',()=>{const {p,service}=fixture(),exit=newRecord('bootstrapExits');service.values.phase='temporary-bootstrap';Object.assign(exit.values,{temporaryService:service.id,permanentService:service.id,observation:'accepted'});p.records.bootstrapExits=[exit];const fields=preparationFindings(p).filter(f=>f.record===exit.id).map(f=>f.field);expect(fields).toEqual(expect.arrayContaining(['permanentService','credentialRotation','accessRemoval','recovery','disposition','observedAt']))})
})
describe('preparation persistence, conditional forms and exports',()=>{
 it('excludes retained automation bindings from the manual bootstrap graph',()=>{const {p,service}=fixture();Object.assign(service.values,{product:'runner',hosting:'target-cluster',hostingResource:''});p.config.bootstrap.runnerComponent=service.id;p.config.bootstrap.mode='existing-automation';expect(preparationGraph(p).blocked).toContain('system:bootstrap');p.config.bootstrap.mode='manual-operator';expect(preparationGraph(p).blocked).toEqual([]);expect(p.config.bootstrap.runnerComponent).toBe(service.id)})
 it('keeps manual bootstrap answers inactive and scopes federation fields to the selected method',()=>{const {p}=fixture();const group=settings.find(g=>g.key==='bootstrap')!,repository=group.fields.find(f=>f.key==='repository')!,issuer=group.fields.find(f=>f.key==='federationIssuer')!;p.config.bootstrap.repository='https://example.test/team/design';expect(fieldApplicable(repository,p.config.bootstrap,p.config)).toBe(false);p.config.bootstrap.mode='existing-automation';expect(fieldApplicable(repository,p.config.bootstrap,p.config)).toBe(true);expect(fieldApplicable(issuer,p.config.bootstrap,p.config)).toBe(true);p.config.bootstrap.authentication='managed-identity';expect(fieldApplicable(issuer,p.config.bootstrap,p.config)).toBe(false)})
 it('rejects mismatched bootstrap service, principal and tool contracts',()=>{const {p,host,service}=fixture(),identity=newRecord('identities'),pin=newRecord('toolPins');identity.values.kind='service-principal';p.records.identities=[identity];Object.assign(p.config.bootstrap,{mode:'existing-automation',runnerComponent:service.id,serviceIdentity:identity.id,authentication:'managed-identity',powershellVersion:'7.5.3',runnerOS:'windows'});Object.assign(pin.values,{executor:host.id,kind:'powershell',version:'7.4.0',operatingSystem:'external-linux'});p.records.toolPins=[pin];const issues=preparationFindings(p);expect(issues.some(f=>f.field==='runnerComponent')).toBe(true);expect(issues.some(f=>f.field==='serviceIdentity'&&f.category==='reference')).toBe(true);expect(issues.some(f=>f.record===pin.id&&f.field==='operatingSystem')).toBe(true);expect(issues.some(f=>f.record===pin.id&&f.message.includes('version disagree'))).toBe(true)})
 it('migrates schema 4 without inventing new permission reviews or hosting observations',()=>{const {p,service}=fixture();p.records.managementHosts=[];service.values.hostingResource='';const old=structuredClone(p);old.schemaVersion=4;for(const g of settings){if((g.since??1)>4){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>4)delete old.config[g.key][f.key];}for(const g of collections){if((g.since??1)>4){delete old.records[g.key];continue}for(const row of old.records[g.key])for(const f of g.fields)if((f.since??1)>4)delete row.values[f.key]}const migrated=parseProject(canonical(old));expect(migrated.schemaVersion).toBe(10);expect(migrated.records.management[0].id).toBe(service.id);expect(migrated.config.bootstrap.accessReview).toBe('unreviewed');expect(migrated.config.bootstrap.permissionReviewAt).toBe('');expect(migrated.records.managementHosts).toEqual([]);old.config.bootstrap.accessReview='operator-reported';expect(()=>parseProject(canonical(old))).toThrow('unknown field')})
 it('retains conditional product fields and removes private observations from sharing',()=>{const {p,service}=fixture();service.values.product='ad-dns';service.values.directoryDomain='private.example';const field=collections.find(g=>g.key==='management')!.fields.find(f=>f.key==='directoryDomain')!;expect(fieldApplicable(field,service.values,p.config)).toBe(true);service.values.product='wac';expect(fieldApplicable(field,service.values,p.config)).toBe(false);expect(parseProject(canonical(p)).records.management[0].values.directoryDomain).toBe('private.example');expect(designMarkdown(p)).toContain('Managed directory domain (retained inactive)');expect(canonical(sanitize(p))).not.toContain('private.example')})
 it('exports the actual graph, owner handoffs and capacity in JSON, schedules and reports',async()=>{const {p,service}=fixture();service.values.owner='Synthetic owner';service.values.requiredBeforeCluster=true;const files=await exportFiles(p,false,false);expect(JSON.parse(String(files['plans/preparation.json']))).toEqual(preparationPlan(p));expect(implementationMarkdown(p)).toContain('Synthetic owner');expect(schedules(p)['Management capacity'][1][2]).toBe(8);expect(JSON.parse(String(files['plans/stages.json'])).preparation.graph.edges).toEqual(preparationGraph(p).edges);expect(JSON.parse(String(files['manifest.json'])).runtimeQualified).toBe(false)})
})
