import { describe,it,expect } from 'vitest'
import { collections,settings } from './catalog'
import { newProject,newRecord,parseProject,canonical,sanitize,MAX_FILE_BYTES } from './project'
import { autosave,restore,DRAFT_KEY } from './persistence'
describe('owned project contract',()=>{
 it('covers fourteen screens and round trips incomplete designs',()=>{expect(new Set([...settings,...collections].map(x=>x.screen)).size).toBe(14);const p=newProject();expect(parseProject(canonical(p))).toEqual(p);expect(p.config.sdn.enabled).toBe(true);expect(newRecord('volumes').values.provisioning).toBe('fixed')})
 it('migrates v1 without inventing evidence or losing identities',()=>{const p=newProject();const old:any=structuredClone(p);old.schemaVersion=1;delete old.evidence;for(const g of collections)if((g.since??1)>1)delete old.records[g.key];for(const g of settings){if((g.since??1)>1){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>1)delete old.config[g.key][f.key];}expect(parseProject(JSON.stringify(old))).toEqual(p);old.evidence=[];expect(()=>parseProject(JSON.stringify(old))).toThrow('unknown field')})
 it('migrates schema 8 designs to schema 9 with safe component defaults and rejects smuggled schema 9 answers',()=>{const p=newProject();const old:any=structuredClone(p);old.schemaVersion=8;for(const g of settings){if((g.since??1)>8){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>8)delete old.config[g.key][f.key]}for(const g of collections)if((g.since??1)>8)delete old.records[g.key];const migrated=parseProject(JSON.stringify(old));expect(migrated).toEqual(p);expect(migrated.config.firewall).toMatchObject({provider:'tierpoint-fortinet',haMode:'active-passive'});expect(migrated.config.tor).toMatchObject({provider:'tierpoint-dell',storageVlans:'711,712',pfcPriority:3});expect(migrated.config.hybrid).toMatchObject({s2sVpn:'unanswered',p2sVpn:'not-used',expressRoute:'not-used'});expect(migrated.config.architecture.sanProtocol).toBe('fc');expect(migrated.records.firewalls).toEqual([]);const smuggled=structuredClone(old);smuggled.config.firewall=p.config.firewall;expect(()=>parseProject(JSON.stringify(smuggled))).toThrow('unknown field');const none=structuredClone(old);none.config.azure.witness='none';expect(()=>parseProject(JSON.stringify(none))).toThrow('newer schema')})
 it('migrates schema 9 designs to schema 10 with an empty switchless cable map and rejects smuggled schema 10 records',()=>{const p=newProject();expect(p.schemaVersion).toBe(10);expect(p.appVersion).toBe('0.4.0');const node=newRecord('nodes');node.values.name='kept-node';p.records.nodes.push(node);p.config.architecture.switching='switchless';const old:any=structuredClone(p);old.schemaVersion=9;for(const g of settings){if((g.since??1)>9){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>9)delete old.config[g.key][f.key]}for(const g of collections)if((g.since??1)>9)delete old.records[g.key];expect(old.records).not.toHaveProperty('storageLinks');const migrated=parseProject(JSON.stringify(old));expect(migrated).toEqual(p);expect(migrated.records.storageLinks).toEqual([]);expect(migrated.records.nodes[0].values.name).toBe('kept-node');const smuggled=structuredClone(old);smuggled.records.storageLinks=[];expect(()=>parseProject(JSON.stringify(smuggled))).toThrow('unknown field');expect(()=>parseProject(JSON.stringify({...old,schemaVersion:11}))).toThrow('1 through 10')})
 it('rejects foreign, future, malformed, huge and unknown-field inputs',()=>{for(const text of ['{}','{',JSON.stringify({...newProject(),schemaVersion:99}),JSON.stringify({...newProject(),password:'anything'})])expect(()=>parseProject(text)).toThrow();expect(()=>parseProject(' '.repeat(MAX_FILE_BYTES+1))).toThrow('limit')})
 it('rejects wrong primitive types, unknown options, nonfinite numbers and duplicate ids',()=>{let p=newProject();p.config.sdn.enabled='true';expect(()=>parseProject(canonical(p))).toThrow('boolean');p=newProject();p.config.architecture.storage='anything';expect(()=>parseProject(canonical(p))).toThrow('choice');p=newProject();const row=newRecord('nodes');p.records.nodes=[row,row];expect(()=>parseProject(canonical(p))).toThrow('duplicate');p=newProject();p.config.capacity.vcpuRatio=Infinity;expect(()=>parseProject(canonical(p))).toThrow('number')})
 it('accepts references and rejects literals and credential-bearing URLs',()=>{for(const value of ['plain-password','https://user:pass@example.test','keyvault://vault/../secret']){const p=newProject();p.config.bootstrap.credentialRef=value;expect(()=>parseProject(canonical(p))).toThrow()}const p=newProject();p.config.bootstrap.credentialRef='keyvault://test-vault/runner';expect(parseProject(canonical(p))).toEqual(p);p.config.bootstrap.repository='https://example.test/file?sig=abc';expect(()=>parseProject(canonical(p))).toThrow('tokens')})
 it('sanitizes free text, observations and provider identities while retaining typed references',()=>{const p=newProject();const node=newRecord('nodes'),port=newRecord('adapters');node.values.name='private-node';node.values.serial='private-serial';port.values.node=node.id;p.records.nodes=[node];p.records.adapters=[port];p.config.project.customer='private-customer';const clean=sanitize(p);expect(canonical(clean)).not.toContain('private-');expect(clean.records.adapters[0].values.node).toBe(clean.records.nodes[0].id);expect(parseProject(canonical(clean))).toEqual(clean)})
 it('does not overwrite corrupt drafts or concurrent changes',()=>{const map=new Map<string,string>();const store={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v)},removeItem:(k:string)=>{map.delete(k)}};map.set(DRAFT_KEY,'{broken');expect(restore(store).corrupt).toBe('{broken');expect(map.get(DRAFT_KEY)).toBe('{broken');expect(()=>autosave(store,newProject(),null)).toThrow('Another tab');const next=autosave(store,newProject(),'{broken');expect(restore(store).project).not.toBeNull();map.set(DRAFT_KEY,'changed');expect(()=>autosave(store,newProject(),next)).toThrow('Another tab')})
})
