import {describe,it,expect} from 'vitest'
import {collections,settings} from './catalog'
import {canonical,newProject,newRecord,parseProject,type Project} from './project'
import {parityFactor,resiliencyFactor,storageBudgets,volumeCost} from './storage'
import {containedDirectory,csvDirectory,storageFindings,validIqn,validWwpn} from './storageRules'
import {previewCsvCount,applyCsvCount} from './storageEditing'
import {storagePlacement} from './storagePlacement'
import {storageAccounting,storageSchedules} from './storageExport'
import {exportFiles,designMarkdown} from './exports'

function poolFixture(count=2,media='ssd',drives=6){
 const p=newProject(),pool=newRecord('pools');pool.values.name='Local pool';p.records.pools=[pool]
 for(let i=0;i<count;i++){const n=newRecord('nodes'),d=newRecord('devices');n.values.name=`Node ${i}`;d.values={...d.values,node:n.id,pool:pool.id,size:1,unit:'TB',count:drives,media};p.records.nodes.push(n);p.records.devices.push(d)}
 return p
}
function csv(p:Project,layout='two-way-mirror'){const row=newRecord('volumes');row.values={...row.values,name:'CSV1',pool:p.records.pools[0]?.id??'',size:1,unit:'TB',resiliency:layout};p.records.volumes.push(row);return row}
function oldSchema(p:Project,version:number){const old=structuredClone(p);old.schemaVersion=version;for(const g of collections){if((g.since??1)>version){delete old.records[g.key];continue}for(const row of old.records[g.key])for(const f of g.fields)if((f.since??1)>version)delete row.values[f.key]}for(const g of settings){if((g.since??1)>version){delete old.config[g.key];continue}for(const f of g.fields)if((f.since??1)>version)delete old.config[g.key][f.key];}return old}

describe('documented storage accounting',()=>{
 it.each([
  [4,2,2],[5,2,2],[6,2,2],[7,1.5,1.5],[8,1.5,1.5],[9,8/6,1.5],[10,8/6,1.5],[11,8/6,1.5],[12,8/6,11/8],[13,8/6,11/8],[14,8/6,11/8],[15,8/6,11/8],[16,15/12,11/8],
 ])('uses the Microsoft flash/HDD table at %s nodes',(nodes,flash,hdd)=>{expect(parityFactor(nodes,'all-flash')).toBe(flash);expect(parityFactor(nodes,'hdd')).toBe(hdd)})
 it('retains unknown media and invalid node counts as unresolved',()=>{expect(parityFactor(9,'unresolved')).toBeNull();for(const n of [0,1,3,17,4.5])expect(parityFactor(n,'all-flash')).toBeNull();for(const n of [2.5,17])expect(resiliencyFactor('two-way-mirror',n,0)).toBeNull()})
 it('reproduces the documented nested 100 GB, six-drive, ten-percent mirror example',()=>{const p=poolFixture(),v=csv(p,'nested-mirror-accelerated-parity');Object.assign(v.values,{size:100,unit:'GB',mirrorPercent:10});expect(volumeCost(p,v).nominalBytes).toBeCloseTo(256e9,0);expect(resiliencyFactor('nested-mirror-accelerated-parity',2,10,'all-flash',3)).toBeNull();expect(resiliencyFactor('nested-mirror-accelerated-parity',2,10,'all-flash',10)).toBeCloseTo(.4+.9*14/6)})
 it('weights actual tier allocation separately from desired logical tier proportion',()=>{const p=poolFixture(4),v=csv(p,'mirror-accelerated-parity');Object.assign(v.values,{size:100,unit:'GB',mirrorPercent:20,allocated:40,mirrorAllocated:20,parityAllocated:20,used:10,mirrorUsed:10,parityUsed:0,provisioning:'thin',allocationBasis:'planned',growthReservePercent:50});const cost=volumeCost(p,v);expect(cost.problems).toEqual([]);expect(cost.nominalBytes).toBeCloseTo(220e9,0);expect(cost.committedBytes).toBe(100e9);expect(cost.usedBytes).toBe(30e9);expect(cost.growthBytes).toBe(50e9);v.values.parityAllocated=19;expect(volumeCost(p,v).problems.join()).toContain('do not sum')})
 it('uses only HDD capacity drives for nested parity on mixed-media pools',()=>{const p=poolFixture(2,'hdd',4);for(const node of p.records.nodes){const d=newRecord('devices');Object.assign(d.values,{node:node.id,pool:p.records.pools[0].id,media:'ssd',count:2,size:1});p.records.devices.push(d)}const v=csv(p,'nested-mirror-accelerated-parity');v.values.mirrorPercent=10;expect(volumeCost(p,v).factor).toBeCloseTo(.4+.9*8/3);for(const d of p.records.devices.filter(d=>d.values.media==='hdd'))d.values.count=3;expect(volumeCost(p,v).factor).toBeNull()})
 it('reserves drive capacity by media once and growth by the greater source or row policy',()=>{const p=poolFixture(2,'hdd',6),pool=p.records.pools[0];pool.values.reserveMode='recommended';pool.values.growthPercent=10;pool.values.metadataPercent=1;for(const node of p.records.nodes){const d=newRecord('devices');Object.assign(d.values,{node:node.id,pool:pool.id,media:'ssd',size:.5,unit:'TB',count:2});p.records.devices.push(d)}const v=csv(p);Object.assign(v.values,{provisioning:'thin',allocationBasis:'planned',allocated:.5,growthReservePercent:20});const b=storageBudgets(p)[0];expect(b.rawBytes).toBe(14e12);expect(b.repairReserveBytes).toBe(3e12);expect(b.metadataBytes).toBe(.14e12);expect(b.committedBytes).toBe(1e12);expect(b.growthBytes).toBe(.2e12);expect(b.remainingBytes).toBe(9.66e12)})
 it('reconciles whole-array observed allocation with existing LUNs and adds new intent only once',()=>{const p=newProject();p.config.architecture.storage='san';const a=newRecord('arrays'),existing=newRecord('luns'),planned=newRecord('luns');Object.assign(a.values,{capacity:100,allocated:60,used:25,telemetryScope:'observed-whole-source',telemetryAt:'2026-09-11T12:00:00Z',telemetryRef:'observation-1'});Object.assign(existing.values,{array:a.id,lifecycle:'reuse',size:30,allocated:20,provisioning:'thin',allocationBasis:'operator-observed',telemetryAt:'2026-09-11T12:00:00Z',telemetryRef:'lun-1'});Object.assign(planned.values,{array:a.id,size:10,provisioning:'thick'});p.records.arrays=[a];p.records.luns=[existing,planned];const b=storageBudgets(p)[0];expect(b.problems).toEqual([]);expect(b.modeledCommittedBytes).toBe(30e12);expect(b.otherCommittedBytes).toBe(40e12);expect(b.remainingBytes).toBe(30e12);expect(b.usedBytes).toBe(25e12);a.values.otherCommittedBytes=1;expect(storageBudgets(p)[0].remainingBytes).toBeNull();a.values.otherCommittedBytes=0;a.values.allocated=10;expect(storageBudgets(p)[0].problems.join()).toContain('less than')})
 it('requires thin allocation basis and does not borrow SAN headroom for S2D',()=>{const p=poolFixture();p.config.architecture.storage='hybrid';const a=newRecord('arrays');a.values.capacity=100;p.records.arrays=[a];const v=csv(p);v.values.size=10;expect(storageBudgets(p).map(b=>b.remainingBytes)).toEqual([-8e12,100e12]);v.values.provisioning='thin';expect(storageBudgets(p)[0].remainingBytes).toBeNull();v.values.allocationBasis='planned';expect(storageBudgets(p)[0].remainingBytes).toBe(12e12);v.values.parityMediaBasis='hdd';expect(storageBudgets(p)[0].remainingBytes).toBeNull()})
 it('does not count a SAN CSV again as another array allocation',()=>{const p=newProject();p.config.architecture.storage='san';const a=newRecord('arrays'),lun=newRecord('luns'),v=newRecord('volumes');a.values.capacity=50;Object.assign(lun.values,{array:a.id,size:10});Object.assign(v.values,{source:'san',lun:lun.id,size:10});p.records.arrays=[a];p.records.luns=[lun];p.records.volumes=[v];expect(storageBudgets(p)[0].committedBytes).toBe(10e12)})
})
describe('storage identity and observation boundaries',()=>{
 it('canonicalizes Windows CSV directories and rejects traversal, prefix confusion and reserved names',()=>{expect(csvDirectory('c:\\ClusterStorage\\Volume1\\')).toBe('c:\\clusterstorage\\volume1');expect(containedDirectory('C:\\ClusterStorage\\Volume1\\VMs','c:\\clusterstorage\\volume1')).toBe(true);expect(containedDirectory('C:\\ClusterStorage\\Volume10','C:\\ClusterStorage\\Volume1')).toBe(false);for(const value of ['C:\\ClusterStorage\\..\\other','C:\\ClusterStorage\\CON','C:\\ClusterStorage\\Volume1.','C:\\ClusterStorage\\\\Volume1','D:\\ClusterStorage\\Volume1'])expect(csvDirectory(value)).toBeNull()})
 it('rejects malformed SAN port identities including arbitrary separators',()=>{for(const value of ['5000000000000001','50:00:00:00:00:00:00:01','50-00-00-00-00-00-00-01'])expect(validWwpn(value)).toBe(true);for(const value of ['::::5000000000000001','50:00-00:00:00:00:00:01','5001'])expect(validWwpn(value)).toBe(false);expect(validIqn('iqn.2026-09.test.example:node1')).toBe(true);expect(validIqn('iqn.2026-13.test.example:node1')).toBe(false)})
 it('rejects reserved CSV placement and mismatch between directory and selected CSV',()=>{const p=poolFixture(),v=csv(p),path=newRecord('storagePaths');Object.assign(v.values,{role:'infrastructure',mount:'C:\\ClusterStorage\\Infrastructure_1'});Object.assign(path.values,{name:'valid-path',volume:v.id,directory:'C:\\ClusterStorage\\Volume1\\VMs',apiVersion:'2024-01-01'});p.records.storagePaths=[path];const issues=storageFindings(p).filter(f=>f.group==='storagePaths');expect(issues.some(f=>f.field==='volume'&&f.category==='support')).toBe(true);expect(issues.some(f=>f.field==='directory')).toBe(true);expect(issues.some(f=>f.field==='subscription')).toBe(true)})
 it('detects repeated MPIO declarations and inconsistent per-node LUN identity and sectors',()=>{const p=poolFixture();p.config.architecture.storage='san';const lun=newRecord('luns');Object.assign(lun.values,{stableId:'disk-1',size:1});p.records.luns=[lun];for(let i=0;i<2;i++){const observation=newRecord('lunPresentations');Object.assign(observation.values,{node:p.records.nodes[i].id,lun:lun.id,visible:true,access:'read-write',observedSize:1,observedStableId:i?'disk-2':'disk-1',sectorBytes:i?4096:512,observedAt:'2026-09-11T12:00:00Z',evidence:'capture-1'});p.records.lunPresentations.push(observation);const path=newRecord('ioPaths');Object.assign(path.values,{node:p.records.nodes[0].id,lun:lun.id,initiator:'same-init',target:'same-target'});p.records.ioPaths.push(path)}const issues=storageFindings(p);expect(issues.some(f=>f.message.includes('Duplicate initiator/target'))).toBe(true);expect(issues.some(f=>f.message.includes('sector sizes differ'))).toBe(true);expect(issues.some(f=>f.group==='lunPresentations'&&f.field==='observedStableId')).toBe(true)})
})
describe('reviewed count changes and schema 4 migration',()=>{
 it('defaults added CSVs to fixed while preserving other sources, inactive rows and platform CSVs',()=>{const p=poolFixture(),platform=csv(p),inactive=csv(p);platform.values.role='infrastructure';inactive.values.lifecycle='not-required';const preview=previewCsvCount(p,'san',2);expect(preview.added.every(r=>r.values.provisioning==='fixed'&&r.values.filesystem==='NTFS'&&r.values.lun==='')).toBe(true);const next=applyCsvCount(p,preview);expect(next.records.volumes).toHaveLength(4);expect(next.records.volumes.slice(0,2)).toEqual(p.records.volumes);expect(p.records.volumes).toHaveLength(2)})
 it('shows exact removals and retains dangling references for correction',()=>{const p=poolFixture(),first=csv(p),last=csv(p),w=newRecord('workloads');w.values.volume=last.id;p.records.workloads=[w];const preview=previewCsvCount(p,'s2d',1);expect(preview.removed.map(r=>r.id)).toEqual([last.id]);expect(preview.references[0]).toMatchObject({group:'workloads',record:w.id,field:'volume',target:last.id});const next=applyCsvCount(p,preview);expect(next.records.volumes.map(r=>r.id)).toEqual([first.id]);expect(next.records.workloads[0].values.volume).toBe(last.id)})
 it('rejects stale previews, fractional and oversized counts',()=>{const p=poolFixture(),preview=previewCsvCount(p,'s2d',2);p.config.project.name='Edited after preview';expect(()=>applyCsvCount(p,preview)).toThrow('changed');for(const n of [-1,1.1,2001,NaN])expect(()=>previewCsvCount(p,'s2d',n)).toThrow('integer')})
 it('migrates schema 3 records without inventing allocation or presentation observations',()=>{const p=poolFixture(),v=csv(p);Object.assign(v.values,{provisioning:'thin',allocated:.3,evidence:'old-source'});const old=oldSchema(p,3),migrated=parseProject(canonical(old));expect(migrated.schemaVersion).toBe(10);expect(migrated.records.volumes[0].id).toBe(v.id);expect(migrated.records.volumes[0].values).toMatchObject({allocated:.3,evidence:'old-source',allocationBasis:'unresolved',telemetryAt:'',telemetryRef:''});expect(migrated.records.lunPresentations).toEqual([]);old.records.volumes[0].values.resiliency='nested-mirror-accelerated-parity';expect(()=>parseProject(canonical(old))).toThrow('newer schema')})
})
describe('logical workload placement and consistent exports',()=>{
 it('reconciles linked management once, includes growth and excludes external storage',()=>{const p=poolFixture(),v=csv(p),m=newRecord('management'),w=newRecord('workloads'),external=newRecord('workloads');Object.assign(m.values,{hosting:'target-cluster',volume:v.id,count:1,diskGiB:100});Object.assign(w.values,{volume:v.id,count:2,storageGiB:60,growthPercent:25,managementComponent:m.id});Object.assign(external.values,{hosting:'external',count:100,storageGiB:1000,externalStorageGiB:500});p.records.management=[m];p.records.workloads=[w,external];const placement=storagePlacement(p);expect(placement.rows).toHaveLength(2);expect(placement.volumes[0].demandBytes).toBe(150*2**30);expect(placement.rows.find(r=>r.record===w.id)?.countedBytes).toBe(0);expect(placement.unplacedBytes).toBe(0)})
 it('requires explicit parent storage inclusion and rejects undersized reservations',()=>{const p=poolFixture(),v=csv(p),parent=newRecord('workloads'),child=newRecord('workloads');Object.assign(parent.values,{volume:v.id,count:1,storageGiB:1000});Object.assign(child.values,{count:2,storageGiB:100,storageAccounting:'included-in-parent',storageIncludedIn:parent.id});p.records.workloads=[parent,child];expect(storagePlacement(p).rows[1].problems.join()).toContain('explicit sizing');child.values.storageAccountingEvidence='PVC sizing included in worker reservation';let placement=storagePlacement(p);expect(placement.rows[1].countedBytes).toBe(0);expect(placement.rows[1].volume).toBe(v.id);expect(placement.volumes[0].demandBytes).toBe(1000*2**30);parent.values.storageGiB=100;placement=storagePlacement(p);expect(placement.volumes[0].resolved).toBe(false);expect(placement.rows[0].problems.join()).toContain('exceeds');parent.values.storageIncludedIn=child.id;parent.values.storageAccounting='included-in-parent';expect(storagePlacement(p).rows.every(r=>r.problems.length>0)).toBe(true)})
 it('flags unplaced demand, conflicting management placement and logical CSV overcommit',()=>{const p=poolFixture(),v=csv(p),other=csv(p),w=newRecord('workloads'),m=newRecord('management');Object.assign(w.values,{count:1,storageGiB:2000});p.records.workloads=[w];expect(storagePlacement(p).unplacedBytes).toBe(2000*2**30);w.values.volume=v.id;expect(storageFindings(p).some(f=>f.message.includes('Placed logical workload demand exceeds'))).toBe(true);Object.assign(m.values,{hosting:'target-cluster',volume:other.id,count:1,diskGiB:100});p.records.management=[m];w.values.managementComponent=m.id;expect(storagePlacement(p).rows.find(r=>r.record===m.id)?.problems.join()).toContain('different CSV')})
 it('exports the same detailed source and CSV accounting in the report, package and schedules',async()=>{const p=poolFixture(),v=csv(p);p.records.pools[0].values.growthPercent=10;const w=newRecord('workloads');Object.assign(w.values,{count:1,storageGiB:100,volume:v.id});p.records.workloads=[w];const data=storageAccounting(p),files=await exportFiles(p,false,false),schedules=storageSchedules(p);expect(JSON.parse(String(files['plans/storage-accounting.json']))).toEqual(data);expect(schedules.Capacity[1][8]).toBe(data.budgets[0].growthBytes);expect(schedules['CSV placement budget'][1][3]).toBe(100*2**30);expect(designMarkdown(p)).toContain(`growth reserve ${data.budgets[0].growthBytes}`);expect(files['schedules/Storage-placement.csv']).toBeDefined()})
})
