import {useState} from 'react'
import type {Project} from './project'
import {activeRecords} from './selectors'
import {applyCsvCount,previewCsvCount,type CsvCountPreview} from './storageEditing'
import {storageBudgets,volumeCost} from './storage'
import {storagePlacement} from './storagePlacement'

export function CsvDesigner({project,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const [source,setSource]=useState<'s2d'|'san'>('s2d'),[count,setCount]=useState(''),[preview,setPreview]=useState<CsvCountPreview|null>(null),[error,setError]=useState('')
 const volumes=activeRecords(project,'volumes'),workloads=volumes.filter(r=>r.values.role==='workload'&&r.values.source===source)
 return <section className="card" aria-label="CSV count designer"><h2>Design the workload CSV count</h2><p>{workloads.length} active {source.toUpperCase()} workload CSVs. Infrastructure and performance-history CSVs are counted separately and retained.</p><div className="fields"><div className="field"><label htmlFor="csv-count-source">CSV count backing source</label><select id="csv-count-source" value={source} onChange={e=>{setSource(e.target.value as 's2d'|'san');setPreview(null)}}><option value="s2d">S2D</option><option value="san">SAN</option></select></div><div className="field"><label htmlFor="csv-count-target">Desired workload CSV count</label><input id="csv-count-target" type="number" min="0" max="2000" step="1" value={count} onChange={e=>{setCount(e.target.value);setPreview(null)}}/></div></div><button onClick={()=>{try{if(count==='')throw new Error('Enter a workload CSV count.');setPreview(previewCsvCount(project,source,Number(count)));setError('')}catch(e){setError((e as Error).message)}}}>Preview CSV count</button>{error&&<p role="alert">{error}</p>}
 {preview&&<section aria-label="CSV count change review" className="notice"><h3>Review CSV count change</h3><p>{preview.added.length} rows to add; {preview.removed.length} rows to remove from the design. New rows use fixed provisioning. Choose each pool or LUN, size, resiliency and mount directory afterward.</p>{preview.added.length>0&&<ul>{preview.added.map(r=><li key={r.id}>Add {String(r.values.name)}</li>)}</ul>}{preview.removed.length>0&&<><p>These exact CSV design rows will be removed. Existing infrastructure is unaffected.</p><ul>{preview.removed.map(r=><li key={r.id}>{String(r.values.name||r.id)} · {String(r.values.lifecycle)} · {r.id}</li>)}</ul></>}{preview.references.length>0&&<><p>The following references are preserved and will need correction:</p><ul>{preview.references.map(r=><li key={`${r.record}-${r.field}`}>{r.group}: {r.name} · {r.field} → {r.target}</li>)}</ul></>}<div className="toolbar"><button onClick={()=>setPreview(null)}>Cancel CSV count change</button><button onClick={()=>{try{onChange(applyCsvCount(project,preview));setPreview(null);setError('')}catch(e){setError((e as Error).message)}}}>Apply reviewed CSV count</button></div></section>}
 <p>Total active CSVs: {volumes.length}; workload: {volumes.filter(r=>r.values.role==='workload').length}; infrastructure: {volumes.filter(r=>r.values.role==='infrastructure').length}; performance history: {volumes.filter(r=>r.values.role==='performance-history').length}. Azure storage paths reference CSV directories and add no capacity.</p></section>
}
const tb=(n:number)=>Number.isFinite(n)?(n/1e12).toLocaleString(undefined,{maximumFractionDigits:3}):'Unresolved'
export function StorageCapacity({project}:{project:Project}){
 const budgets=storageBudgets(project),placement=storagePlacement(project)
 return <><div className="table-wrap"><table><caption>Independent storage source budgets · decimal TB</caption><thead><tr><th>Source</th><th>Capacity</th><th>Repair + metadata</th><th>Listed commitments</th><th>Outside commitments</th><th>Growth reserve</th><th>Nominal potential</th><th>Headroom</th></tr></thead><tbody>{budgets.map(b=><tr key={b.id}><th>{b.name||b.id} ({b.source})</th><td>{tb(b.rawBytes)}</td><td>{tb(b.reserveBytes)}</td><td>{tb(b.modeledCommittedBytes)}</td><td>{tb(b.otherCommittedBytes)}</td><td>{tb(b.growthBytes)}</td><td>{tb(b.nominalBytes)}</td><td>{b.remainingBytes===null?'Unresolved':tb(b.remainingBytes)}</td></tr>)}</tbody></table></div>
 {budgets.map(b=><details key={b.id}><summary>{b.name||b.id}: accounting basis and policies</summary><p>{b.evidenceClass}. Nominal ratio: {b.nominalOvercommitRatio?.toFixed(2)??'Unresolved'}; configured limit: {b.maxOvercommit}. Alert at {b.alertPercent}% allocated capacity.</p><p>Recommended S2D drive repair reserve: {tb(b.recommendedRepairBytes)} TB. Selected repair reserve: {tb(b.repairReserveBytes)} TB. Metadata reserve: {tb(b.metadataBytes)} TB.</p>{b.problems.length>0&&<ul>{b.problems.map((problem,i)=><li key={i}>{problem}</li>)}</ul>}</details>)}
 <div className="table-wrap"><table><caption>CSV logical sizing and backing footprint · decimal TB</caption><thead><tr><th>CSV</th><th>Source</th><th>Logical size</th><th>Physical factor</th><th>Committed</th><th>Nominal potential</th></tr></thead><tbody>{activeRecords(project,'volumes').map(row=>{const c=volumeCost(project,row);return <tr key={row.id}><th>{String(row.values.name||row.id)}</th><td>{c.source}</td><td>{tb(c.logicalBytes)}</td><td>{c.factor?.toFixed(3)??'Unresolved'}</td><td>{c.problems.length?'Unresolved':tb(c.committedBytes)}</td><td>{c.factor===null?'Unresolved':tb(c.nominalBytes)}</td></tr>})}</tbody></table></div><p>Array capacity is usable capacity after array protection. SAN CSV footprints consume their LUNs; they are not added a second time to the array budget. Growth uses the greater of source reserve and summed row reserves. Observations remain operator supplied and unverified.</p><div className="table-wrap"><table><caption>Logical workload placement · decimal TB</caption><thead><tr><th>CSV</th><th>Logical size</th><th>Placed demand with growth</th><th>Logical headroom</th></tr></thead><tbody>{placement.volumes.map(v=><tr key={v.id}><th>{v.name}</th><td>{tb(v.logicalBytes)}</td><td>{tb(v.demandBytes)}</td><td>{v.resolved?tb(v.remainingBytes):'Unresolved'}</td></tr>)}</tbody></table></div><p>Unplaced logical demand: {tb(placement.unplacedBytes)} TB. Workload occupancy is compared with CSV logical size; it is not added again to the source footprint.</p>{placement.rows.map(r=><details key={r.record}><summary>{r.name}: {tb(r.countedBytes)} TB counted</summary><p>{r.basis}. Logical request including growth: {tb(r.logicalBytes)} TB.</p>{r.problems.map((problem,i)=><p key={i}>{problem}</p>)}</details>)}</>
 }
