import type {Project} from './project'
import type {Finding} from './assessment'
import {toolkitReview} from './toolkitMapping'
import {toolkitBridgeReview} from './toolkitBridge'
export function ToolkitPanel({project,onCorrect}:{project:Project;onCorrect:(finding:Finding)=>void}){
 const review=toolkitReview(project),conversion=toolkitBridgeReview(project)
 if(!review.requested)return null
 return <section className="card" aria-label="Toolkit hierarchy review"><h2>Toolkit hierarchy review</h2><p><strong>Design-only · native reader blocked · runtime unqualified</strong></p><p>Source schema v{review.source.schemaVersion}, commit <code>{review.source.commit}</code>. Scenario: {review.scenario??'No declared hybrid scenario'}. Schema assertions: {review.candidateInfrastructure?(review.schemaValid?'passed for this draft':'failed for this draft'):'not evaluated'}.</p><p>The private package contains the canonical hierarchy draft and its mapping review. A schema pass does not establish compatibility with the saved PowerShell reader.</p><details><summary>Source conflicts and reader evidence</summary><ul>{review.sourceFindings.map(f=><li key={f}>{f}</li>)}</ul></details>
 <ul>{review.findings.map(f=><li key={f.id}>{f.message} <button onClick={()=>onCorrect(f)}>Correct {f.group}.{f.field}</button></li>)}</ul>
 <details><summary>Hierarchy mappings ({review.mappings.length})</summary><div className="table-wrap"><table><caption>Toolkit canonical hierarchy mapping</caption><thead><tr><th>Target</th><th>Design source</th><th>Records</th></tr></thead><tbody>{review.mappings.map((m,i)=><tr key={i}><th>{m.target}</th><td>{m.source}</td><td>{m.recordIds.join(', ')}</td></tr>)}</tbody></table></div></details><details><summary>Unmapped stages and contracts</summary><ul>{review.unmapped.map(f=><li key={f}>{f}</li>)}</ul></details>
 <h3>Toolkit conversion data</h3><p>{conversion.qualification} · deployment unqualified</p><p>{conversion.boundary}</p>{conversion.conversionCandidate?<p>The private export includes the Toolkit hierarchy, its companion, pinned schemas and a finished ARM parameter file at inputs/arm/azuredeploy.parameters.json.</p>:<ul>{conversion.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}<details><summary>Canonical and companion parameter sources ({conversion.parameters.length})</summary><div className="table-wrap"><table><caption>Local conversion parameter sources</caption><thead><tr><th>Parameter</th><th>Source</th></tr></thead><tbody>{conversion.parameters.map(m=><tr key={m.parameter}><th>{m.parameter}</th><td>{m.source}</td></tr>)}</tbody></table></div></details></section>
}
