import {test,expect} from '@playwright/test'
import {newProject,canonical} from '../src/project'
import {executionHandoff} from '../src/evidence'
import {readFile} from 'node:fs/promises'
const step=(page:any,name:string)=>page.getByRole('navigation',{name:'Design steps'}).getByRole('button',{name:new RegExp(name)})
test('external evidence is reviewed, retained, reconciled and reopened without runtime claims',async({page})=>{
 const p=newProject(),r=executionHandoff(p).receiptTemplate;r.source='Synthetic browser receipt';r.activityId='synthetic-activity';r.result='succeeded';r.observations=[{group:'project',record:'',field:'name',expected:'',observed:'Reviewed observation'}]
 await page.goto('./');let chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Open design',exact:true}).click();await(await chooser).setFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(canonical(p))});await page.getByRole('button',{name:'Open reviewed design',exact:true}).click();await step(page,'Review and export').click();const panel=page.getByRole('region',{name:'Execution evidence and reconciliation'});chooser=page.waitForEvent('filechooser');await panel.getByRole('button',{name:'Import execution receipt',exact:true}).click();await(await chooser).setFiles({name:'receipt.json',mimeType:'application/json',buffer:Buffer.from(canonical(r))});await expect(panel).toContainText('Baseline matches.');await panel.getByRole('button',{name:'Retain receipt without changing intent'}).click();await step(page,'Project and import').click();await expect(page.getByLabel('Project name',{exact:false})).toHaveValue('');await step(page,'Review and export').click();await panel.locator('summary').click();await panel.getByRole('button',{name:'Adopt observed value into design'}).click();await expect(panel).toContainText('Receipt remains unverified.');await expect(page.getByRole('status')).toContainText('Draft saved');await page.reload();await expect(page.getByLabel('Project name',{exact:false})).toHaveValue('Reviewed observation');const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const file=await wait,json=JSON.parse(await readFile((await file.path())!,'utf8'));expect(json.evidence).toHaveLength(1);expect(json.evidence[0].verification).toBe('unverified');expect(json.evidence[0].projectRevision).toBe(p.revision)
})
test('blocked browser storage still permits editing and project download',async({page})=>{
 await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage is disabled','SecurityError')}}));await page.goto('./');await page.getByRole('button',{name:'Create a deployment design'}).click();await page.getByLabel('Project name',{exact:false}).fill('Portable design');await expect(page.getByRole('status')).toContainText('Browser storage unavailable');const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const file=await wait;expect(JSON.parse(await readFile((await file.path())!,'utf8')).config.project.name).toBe('Portable design')
})
test('Portal choices preserve fixed-layout handoff and identity-specific instructions on mobile',async({page})=>{
 await page.goto('./');await step(page,'Architecture and deployment').click();const panel=page.getByRole('region',{name:'Portal deployment choices'});await expect(panel).toBeVisible();await page.getByLabel('Deployment volume configuration',{exact:true}).selectOption('InfraOnly');await panel.getByText('6. Advanced',{exact:true}).click();await expect(panel).toContainText('infrastructure volumes only');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await panel.screenshot({path:'.artifacts/browser/azurelocal-portal-mobile.png'});await expect(page.getByRole('status')).toContainText('Draft saved');await page.reload();await step(page,'Architecture and deployment').click();await expect(page.getByLabel('Deployment volume configuration',{exact:true})).toHaveValue('InfraOnly')
})
test('corrupt drafts can be downloaded before a reviewed replacement',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('azurelocal-configurator:draft:v2','{broken-original'))
 await page.goto('./');await expect(page.getByRole('status')).toContainText('Saved draft could not be opened');const wait=page.waitForEvent('download');await page.getByRole('button',{name:'Download corrupt draft'}).click();expect(await readFile((await(await wait).path())!,'utf8')).toBe('{broken-original');await page.getByRole('button',{name:'New design',exact:true}).click();await page.getByRole('button',{name:'Open reviewed design'}).click();await page.getByLabel('Project name',{exact:false}).fill('Recovered draft');await expect(page.getByRole('status')).toContainText('Draft saved');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('azurelocal-configurator:draft:v2')!).config.project.name)).toBe('Recovered draft')
})
test('DSC selection retains an explicit design-only resource request',async({page})=>{
 await page.goto('./');await step(page,'Review and export').click();await page.getByLabel('DSC selection',{exact:true}).selectOption('dsc-v3-design-handoff');await page.getByLabel('Exact requested DSC version',{exact:true}).fill('3.0.0');await page.getByLabel('DSC stage, target and preservation boundary',{exact:true}).fill('External review only; preserve existing hosts');await page.getByRole('button',{name:'Add Requested DSC resource contracts',exact:true}).click();const panel=page.getByRole('region',{name:'Requested DSC resource contracts',exact:true});await expect(panel).toContainText('No DSC resource is deployment-qualified');await expect(page.getByText('The selected DSC stage is a design-only handoff.',{exact:false}).first()).toBeVisible();await expect(page.getByRole('status')).toContainText('Draft saved');await page.reload();await step(page,'Review and export').click();await expect(page.getByLabel('DSC selection',{exact:true})).toHaveValue('dsc-v3-design-handoff')
})
