/**
 * Workload-based volume suggestions (#68).
 *
 * Each enabled workload generates one or more suggested volumes
 * that the user can review and add to their volume plan.
 * SOFS and MABS volumes account for internal mirror compounding (#69, #70).
 */
import type {
  VolumeSpec,
  ResiliencyType,
  AdvancedSettings,
} from './types'
import type { AvdResult } from './types'
import type { AksInputs, AksResult } from './types'
import type { SofsResult, SofsInputs } from './types'
import type { MabsResult, MabsInputs } from './types'
import type { VmScenario } from './types'
import type { ServicePresetInstance, } from './service-presets'
import { getCatalogEntry, computeServicePreset } from './service-presets'
import type { CustomWorkload } from './types'
import { computeInventory, WORKLOAD_TIERS, type InventoryVm, type InventorySettings } from './inventory'

export interface SuggestedVolume extends VolumeSpec {
  source: string      // which workload generated this suggestion
  description: string // brief explanation
}

interface WorkloadVolumeInputs {
  inventory?: InventoryVm[]
  inventorySettings?: InventorySettings
  advanced: AdvancedSettings
  // AVD
  avdEnabled: boolean
  avdResult: AvdResult
  // AKS — per-cluster volumes; aksResult used for aksEnabled check
  aksEnabled: boolean
  aksResult: AksResult
  aksInputs?: AksInputs
  // Virtual Machines
  virtualMachines: VmScenario
  // SOFS
  sofsEnabled: boolean
  sofsInputs: SofsInputs
  sofsResult: SofsResult
  // MABS
  mabsEnabled: boolean
  mabsInputs: MabsInputs
  mabsResult: MabsResult
  // Service presets
  servicePresets?: ServicePresetInstance[]
  // Custom workloads
  customWorkloads?: CustomWorkload[]
}

let _sugId = 1000

function round2(n: number): number {
  return Math.round(n * 100) / 100
}

export function generateWorkloadVolumes(inputs: WorkloadVolumeInputs): SuggestedVolume[] {
  const suggestions: SuggestedVolume[] = []
  const defaultRes = inputs.advanced.defaultResiliency

  // ── AVD ──────────────────────────────────────────────────────────────────
  // Per-pool OS + DataDisk volumes (12D addendum): one CSV per session host pool,
  // matching how VM groups work. Profiles and OfficeContainers stay as aggregates
  // because they live on a shared SOFS share, not per-pool.
  if (inputs.avdEnabled) {
    const avd = inputs.avdResult
    for (const pool of avd.pools) {
      const safeName = pool.name.replace(/[^a-zA-Z0-9-]/g, '').slice(0, 24) || `Pool${pool.id}`
      if (pool.totalOsStorageTB > 0) {
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `AVD-${safeName}-OS`,
          resiliency: 'three-way-mirror' as ResiliencyType,
          provisioning: 'fixed',
          plannedSizeTB: round2(pool.totalOsStorageTB),
          source: 'AVD',
          description: `${pool.sessionHostCount} hosts × ${pool.osDiskPerHostGB} GB OS — ${pool.name}`,
        })
      }
      if (pool.dataDiskPerHostGB > 0 && pool.totalDataDiskStorageTB > 0) {
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `AVD-${safeName}-DataDisks`,
          resiliency: defaultRes,
          provisioning: 'fixed',
          plannedSizeTB: round2(pool.totalDataDiskStorageTB),
          source: 'AVD',
          description: `Data disks for ${pool.sessionHostCount} hosts — ${pool.name}`,
        })
      }
    }
    // #151: Only generate profile/OfficeContainer volumes for pools not using SOFS storage.
    // When profileStorageLocation === 'sofs', those profiles live on the SOFS-ProfileData
    // CSV generated by the SOFS section — generating them here would double-count.
    const nonSofsPools = avd.pools.filter((p) => p.profileStorageLocation !== 'sofs')
    const nonSofsProfileTB = nonSofsPools.reduce((sum, p) => sum + p.profileStorageWithGrowthTB, 0)
    const nonSofsOfficeTB = nonSofsPools.reduce((sum, p) => sum + p.totalOfficeContainerStorageTB, 0)
    if (nonSofsProfileTB > 0) {
      suggestions.push({
        id: `sug-${_sugId++}`,
        name: 'AVD-Profiles',
        resiliency: defaultRes,
        provisioning: 'fixed',
        plannedSizeTB: round2(nonSofsProfileTB),
        source: 'AVD',
        description: `FSLogix profiles (${nonSofsPools.length} non-SOFS pool${nonSofsPools.length !== 1 ? 's' : ''}, with growth buffer)`,
      })
    }
    if (nonSofsOfficeTB > 0) {
      suggestions.push({
        id: `sug-${_sugId++}`,
        name: 'AVD-OfficeContainers',
        resiliency: defaultRes,
        provisioning: 'fixed',
        plannedSizeTB: round2(nonSofsOfficeTB),
        source: 'AVD',
        description: `FSLogix Office Container VHDXs (${nonSofsPools.length} non-SOFS pool${nonSofsPools.length !== 1 ? 's' : ''})`,
      })
    }
  }

  // ── AKS ──────────────────────────────────────────────────────────────────
  // One OS-disk volume and one PVC volume per cluster. Arc service preset storage
  // is folded into a combined AKS-ArcServices-PVC entry (no standalone Svc-* volumes
  // for AKS-dependent presets). Resiliency defaults to three-way-mirror for OS disks
  // and defaultRes for PVCs; users can change on Volumes page.
  if (inputs.aksEnabled && inputs.aksInputs) {
    for (const cluster of inputs.aksInputs.clusters) {
      const totalClusterNodes = cluster.controlPlaneNodesPerCluster + cluster.workerNodesPerCluster
      const clusterOsDiskTB = round2((totalClusterNodes * cluster.osDiskPerNodeGB) / 1024)
      const safeName = cluster.name.replace(/[^a-zA-Z0-9]/g, '').slice(0, 20) || `Cluster${cluster.id}`
      if (clusterOsDiskTB > 0) {
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `AKS-${safeName}-OS`,
          resiliency: 'three-way-mirror',
          provisioning: 'fixed',
          plannedSizeTB: clusterOsDiskTB,
          source: 'AKS',
          description: `OS disks for ${totalClusterNodes} nodes — ${cluster.name}`,
        })
      }
      if (cluster.persistentVolumesTB > 0) {
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `AKS-${safeName}-PVC`,
          resiliency: defaultRes,
          provisioning: 'fixed',
          plannedSizeTB: round2(cluster.persistentVolumesTB),
          source: 'AKS',
          description: `Persistent volume claims — ${cluster.name}`,
        })
      }
    }

    // Arc service preset storage flows as PVC storage on AKS worker nodes
    let arcPvcTB = 0
    for (const inst of inputs.servicePresets ?? []) {
      if (!inst.enabled || inst.instanceCount <= 0) continue
      const entry = getCatalogEntry(inst.catalogId)
      if (entry?.requiresAks) {
        arcPvcTB = round2(arcPvcTB + computeServicePreset(inst).totalStorageTB)
      }
    }
    if (arcPvcTB > 0) {
      suggestions.push({
        id: `sug-${_sugId++}`,
        name: 'AKS-ArcServices-PVC',
        resiliency: 'three-way-mirror',
        provisioning: 'fixed',
        plannedSizeTB: arcPvcTB,
        source: 'AKS',
        description: 'Persistent volume claims for Arc-enabled service presets',
      })
    }
  }

  // ── Virtual Machines ─────────────────────────────────────────────────────
  // One volume suggestion per storage group. Resiliency defaults to defaultRes
  // (user can adjust per-volume on the Volumes page).
  if (inputs.virtualMachines?.enabled) {
    for (const group of inputs.virtualMachines.groups) {
      const storageTB = round2((group.vmCount * group.storagePerVmGB) / 1024)
      if (storageTB > 0) {
        const safeName = group.name.replace(/[^a-zA-Z0-9]/g, '').slice(0, 20) || 'Default'
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `VM-${safeName}`,
          resiliency: defaultRes,
          provisioning: 'fixed',
          plannedSizeTB: storageTB,
          source: 'Virtual Machines',
          description: `${group.vmCount} VMs × ${group.storagePerVmGB} GB storage — ${group.name}`,
        })
      }
    }
  }

  // ── SOFS ─────────────────────────────────────────────────────────────────
  // SOFS internal mirror compounds: the Azure Local CSV volume must hold the
  // internal footprint (logical × mirror factor), not just logical data.
  // The guest VM OS disk files and the guest data VHDX files live on the same
  // Azure Local host CSV, so the suggested host-side volume should be combined.
  // Volume layout: 'shared' → 1 combined SOFS volume; 'per-vm' → N combined
  // volumes, one per SOFS guest VM.
  if (inputs.sofsEnabled) {
    const sofs = inputs.sofsResult
    const sofsIn = inputs.sofsInputs
    const vmCount = Math.max(1, sofsIn.sofsGuestVmCount)
    const osDiskGB = Math.max(0, sofsIn.sofsOsDiskPerVmGB ?? 127)
    const mirrorLabel = sofsIn.internalMirror === 'simple'
      ? '' : ` (includes ${sofs.internalMirrorFactor}× internal mirror)`

    if (sofsIn.volumeLayout === 'per-vm') {
      // Per-VM: one combined Azure Local volume per SOFS guest VM
      const perVmDataTB = vmCount > 0 ? round2(sofs.internalFootprintTB / vmCount) : 0
      const perVmOsTB = round2(osDiskGB / 1024)
      const perVmCombinedTB = round2(perVmDataTB + perVmOsTB)
      for (let i = 1; i <= vmCount; i++) {
        if (perVmCombinedTB > 0) {
          suggestions.push({
            id: `sug-${_sugId++}`,
            name: `SOFS-VM${i}`,
            resiliency: defaultRes,
            provisioning: 'fixed',
            plannedSizeTB: perVmCombinedTB,
            source: 'SOFS',
            description: `VM ${i} data share${mirrorLabel}${perVmOsTB > 0 ? ` + ${osDiskGB} GB guest OS disk` : ''}`,
          })
        }
      }
    } else {
      // Shared: one combined Azure Local volume containing guest OS disks + data VHDXs
      const totalOsDiskTB = round2((vmCount * osDiskGB) / 1024)
      const totalCombinedTB = round2(sofs.internalFootprintTB + totalOsDiskTB)
      if (totalCombinedTB > 0) {
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: 'SOFS-Shared',
          resiliency: defaultRes,
          provisioning: 'fixed',
          plannedSizeTB: totalCombinedTB,
          source: 'SOFS',
          description: `${sofs.totalStorageTB} TB logical data${mirrorLabel}${totalOsDiskTB > 0 ? ` + ${vmCount} SOFS VM${vmCount > 1 ? 's' : ''} × ${osDiskGB} GB guest OS disk` : ''}`,
        })
      }
    }
  }

  // ── MABS ─────────────────────────────────────────────────────────────────
  // MABS internal Storage Spaces mirror compounds similarly.
  // Volume resiliency is now per-volume (defaults to advanced.defaultResiliency).
  // MABS-BackupData provisioning defaults to 'thin' (grows over retention period).
  if (inputs.mabsEnabled) {
    const mabs = inputs.mabsResult
    const mirrorFactor = mabs.internalMirrorFactor

    if (mabs.scratchVolumeTB > 0) {
      const scratchDisk = round2(mabs.scratchVolumeTB * mirrorFactor)
      suggestions.push({
        id: `sug-${_sugId++}`,
        name: 'MABS-Scratch',
        resiliency: defaultRes,
        provisioning: 'fixed',
        plannedSizeTB: scratchDisk,
        source: 'MABS',
        description: `Scratch/cache ${mabs.scratchVolumeTB} TB × ${mirrorFactor} mirror`,
      })
    }
    if (mabs.backupDataVolumeTB > 0) {
      const backupDisk = round2(mabs.backupDataVolumeTB * mirrorFactor)
      suggestions.push({
        id: `sug-${_sugId++}`,
        name: 'MABS-BackupData',
        resiliency: defaultRes,
        provisioning: 'thin',
        plannedSizeTB: backupDisk,
        source: 'MABS',
        description: `Backup data ${mabs.backupDataVolumeTB} TB × ${mirrorFactor} mirror`,
      })
    }
    if (mabs.mabsOsDiskTB > 0 && (inputs.mabsInputs.mabsOsDiskPlacement ?? 'dedicated') !== 'shared') {
      suggestions.push({
        id: `sug-${_sugId++}`,
        name: 'MABS-OsDisk',
        resiliency: 'three-way-mirror',
        provisioning: 'fixed',
        plannedSizeTB: round2(mabs.mabsOsDiskTB),
        source: 'MABS',
        description: 'MABS VM operating system disk',
      })
    }
  }

  // ── Service Presets ───────────────────────────────────────────────────────
  // AKS-dependent presets have their storage folded into AKS-ArcServices-PVC above.
  // Only non-AKS presets (if any exist) get standalone volume suggestions here.
  if (inputs.servicePresets && inputs.servicePresets.length > 0) {
    for (const inst of inputs.servicePresets) {
      if (!inst.enabled || inst.instanceCount <= 0) continue
      const entry = getCatalogEntry(inst.catalogId)
      if (!entry) continue
      // Skip AKS-dependent presets when AKS is enabled — storage already in AKS-ArcServices-PVC
      if (entry.requiresAks && inputs.aksEnabled) continue
      const t = computeServicePreset(inst)
      if (t.totalStorageTB > 0) {
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `Svc-${entry.shortName.replace(/[^a-zA-Z0-9]/g, '')}`,
          resiliency: entry.defaultPvcResiliency,
          provisioning: 'fixed',
          plannedSizeTB: round2(t.totalStorageTB),
          source: 'Service Presets',
          description: `${entry.shortName} × ${inst.instanceCount} — ${t.totalVCpus} vCPU, ${t.totalMemoryGB} GB`,
        })
      }
    }
  }

  // ── Custom Workloads ──────────────────────────────────────────────────────
  // OS disks → Three-Way Mirror; data volumes → defaultResiliency.
  // Internal mirror compounding: volume suggestion = storageTB × mirrorFactor.
  if (inputs.customWorkloads && inputs.customWorkloads.length > 0) {
    for (const wl of inputs.customWorkloads) {
      if (!wl.enabled) continue
      const safeName = wl.name.replace(/[^a-zA-Z0-9]/g, '').slice(0, 20) || 'Custom'
      if (wl.osDiskPerVmGB > 0 && wl.vmCount > 0) {
        const osTB = round2((wl.vmCount * wl.osDiskPerVmGB) / 1024)
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `${safeName}-OsDisk`,
          resiliency: 'three-way-mirror',
          provisioning: 'fixed',
          plannedSizeTB: osTB,
          source: 'Custom Workloads',
          description: `${wl.vmCount} VMs × ${wl.osDiskPerVmGB} GB OS disk — ${wl.name}`,
        })
      }
      if (wl.storageTB > 0) {
        const footprint = round2(wl.storageTB * wl.internalMirrorFactor)
        const mirrorNote = wl.internalMirrorFactor > 1
          ? ` (${wl.storageTB} TB × ${wl.internalMirrorFactor} internal mirror)`
          : ''
        suggestions.push({
          id: `sug-${_sugId++}`,
          name: `${safeName}-Data`,
          resiliency: defaultRes,
          provisioning: 'fixed',
          plannedSizeTB: footprint,
          source: 'Custom Workloads',
          description: `${wl.name}${mirrorNote}`,
        })
      }
    }
  }

  const inventory = computeInventory(inputs.inventory, inputs.inventorySettings)
  for (const tier of WORKLOAD_TIERS) {
    const size = inventory.storageByTier[tier]
    if (size <= 0) continue
    // Split inventory volumes at the existing planner's 64 TB volume ceiling.
    // Keep extreme inputs bounded; an oversized remainder is rejected by fit/volume validation.
    const count = Math.min(256, Math.ceil(size / 64))
    for (let i = 0; i < count; i++) {
      suggestions.push({
        id: `inventory-${tier}-${i + 1}`, name: `Inventory-${tier}-${i + 1}`,
        resiliency: defaultRes, provisioning: 'fixed',
        plannedSizeTB: Math.ceil(size / count * 100) / 100,
        source: 'VM inventory',
        description: `${tier} inventory; ${inputs.inventorySettings?.storageBasis ?? 'provisioned'} storage, including inventory growth. GiB converted to decimal TB.`,
      })
    }
  }
  return suggestions
}
